### ISSUE TITLE
c++17 incompatibility in Triangulation_3.h

### ISSUE THREAD

**Issue by acgetchell** [CGAL/cgal#2974]
## Issue Details

/usr/local/bin/cmake --build /Users/adam/CDT-plusplus/build --target all -- -j 4
Scanning dependencies of target cdt
Scanning dependencies of target cdt-opt
Scanning dependencies of target cdt-gv
[ 40%] Building CXX object CMakeFiles/cdt-opt.dir/src/date/src/tz.cpp.o
[ 40%] Building CXX object CMakeFiles/cdt.dir/src/cdt.cpp.o
[ 40%] Building CXX object CMakeFiles/cdt-gv.dir/src/cdt-gv.cpp.o
[ 40%] Building CXX object CMakeFiles/cdt-opt.dir/src/cdt-opt.cpp.o
In file included from /Users/adam/CDT-plusplus/src/cdt-opt.cpp:21:
In file included from /Users/adam/CDT-plusplus/include/Measurements.hpp:18:
In file included from /Users/adam/CDT-plusplus/include/SimplicialManifold.hpp:23:
In file included from /Users/adam/CDT-plusplus/include/S3Triangulation.hpp:45:
In file included from /usr/local/include/CGAL/Delaunay_triangulation_3.h:40:
In file included from /usr/local/include/CGAL/Triangulation_3.h:50:
In file included from /usr/local/include/CGAL/spatial_sort.h:25:
/usr/local/include/CGAL/hilbert_sort.h:56:9: error: no member named 'random_shuffle' in namespace 'std'; did you mean simply 'random_shuffle'?
        std::random_shuffle(begin,end, rng);

## Source Code

https://github.com/acgetchell/CDT-plusplus

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): MacOS 10.13.4
* Compiler: Apple LLVM version 9.1.0 (clang-902-0.39.1)
* Release or debug mode: both
* Specific flags used (if any): -DCGAL_TRIANGULATION_NO_ASSERTIONS -DCGAL_TRIANGULATION_NO_POSTCONDITIONS -Wall -Wno-comment --std=c++17 (from CMAKE target_compile_features cxx_std_17, although that might be passing --std=c++1z instead)
* CGAL version: 4.11.1
* Boost version: 1.66.0
* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3.3.4, TBB 2018_U3

**Comment by acgetchell** [comment]
This error goes away if I set to C++14 using target_compile_features(cdt PRIVATE cxx_std_14)

**Comment by acgetchell** [comment]
Looks like this can be fixed by swapping std::random_shuffle with std::shuffle, e.g. clang-tidy modernize-replace-random-shuffle

**Comment by lrineau** [comment]
I think that is something that has been done for CGAL 4.12. You should try with CGAL-4.12-beta1.

**Comment by acgetchell** [comment]
Tried CGAL-4.12-beta1, still same issues.

**Comment by lrineau** [comment]
Indeed. I had the sensation of déjà-vu, but I cannot find anything. Maybe I was aware of the deprecation, but forgot to fill the issue and the PR.

**Comment by lrineau** [comment]
@afabri I think the moment when we saw that error with `random_shuffle` being removed from C++17 was when we tried MSVC 2017 with C++17 (compilation flag `/std:c++latest`).

It seems Boost 1.67 beta [is supposed to support it Apple Clang 9.00 with C++17][*] so that means that they have removed their internal uses of functions removed from C++17.

  [*]: https://www.boost.org/users/history/version_1_67_0.html

That is something that we could try, locally: compile with MSVC 2017, Boost 1.67, and `/std:c++latest` in the compilation flags. What would be a way to detect the problems with C++17.

In [CGAL-4.12-Ic-57](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-57/), when we tried first, here were the errors (counted and sorted by number of occurrences):
```
     42 error C2039: 'ptr_fun': is not a member of 'std'
    142 error C2039: 'binary_function': is not a member of 'std'
    199 error C2039: 'binder1st': is not a member of 'std'
    199 error C2039: 'binder2nd': is not a member of 'std'
    215 error C2039: 'random_shuffle': is not a member of 'std'
    520 error C2039: 'auto_ptr': is not a member of 'std'
    817 error C2039: 'unary_function': is not a member of 'std'
```
There error with `random_shuffle` was detected in [Triangulation_3], but also in:
- `AABB_tree`
- `Advancing_front_surface_reconstruction_Examples`
- `Advancing_front_surface_reconstruction`
- `Alpha_shapes_2_Demo`
- `Alpha_shapes_2_Examples`
- `Alpha_shapes_2`
- `Alpha_shapes_3_Demo`
- `Alpha_shapes_3_Examples`
- `Alpha_shapes_3`
- `Arrangement_on_surface_2_Examples`
- `Arrangement_on_surface_2`
- `Bounding_volumes`
- `Convex_hull_3_Examples`
- `Convex_hull_3`
- `Generator_Examples`
- `Generator`
- `Interval_skip_list_Examples`
- `Interval_skip_list`
- `Min_annulus_d_Examples`
- `Min_circle_2_Examples`
- `Min_ellipse_2_Examples`
- `Periodic_2_triangulation_2_Demo`
- `Periodic_2_triangulation_2_Examples`
- `Periodic_2_triangulation_2`
- `Periodic_3_triangulation_3_Demo`
- `Periodic_3_triangulation_3_Examples`
- `Periodic_3_triangulation_3`
- `Periodic_Lloyd_3_Demo`
- `Point_set_2_Examples`
- `Point_set_2`
- `Polygon_mesh_processing`
- `Polytope_distance_d_Examples`
- `Polytope_distance_d`
- `QP_solver_Examples`
- `QP_solver`
- `Random_numbers`
- `Segment_Delaunay_graph_2_Examples`
- `Segment_Delaunay_graph_2`
- `Segment_Delaunay_graph_Linf_2_Examples`
- `Segment_Delaunay_graph_Linf_2`
- `Skin_surface_3_Examples`
- `Skin_surface_3`
- `Spatial_sorting_Examples`
- `Spatial_sorting`
- `STL_Extension`
- `Triangulation_2_Demo`
- `Triangulation_2_Examples`
- `Triangulation_2`
- `Triangulation_3_Demo`
- `Triangulation_3_Examples`
- `Triangulation_3`
- `Visibility_2_Examples`
- `Visibility_2`
- `Voronoi_diagram_2`

[Triangulation_3]: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-57/Triangulation_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits-extra_flags.gz

I think supporting C++17 should be a goal for CGAL-4.12, as soon as Boost 1.67 is released (planned in 10 days). If we can reproduce the errors with MSVC 2017, that will be easier than working with Apple Clang 9.0 on a Mac Mini.
