### ISSUE TITLE
Compilation error when using `CGAL::remove_outliers` with `CGAL::named_parameters::point_map`

### ISSUE THREAD

**Issue by cjamin** [CGAL/cgal#5008]
Looks like the changes introduced by commit https://github.com/CGAL/cgal/commit/82479e780bdaeb4c7257a3a1593f2e68e638d24e forbid the use of `CGAL::named_parameters::point_map` as a parameter of `CGAL::remove_outliers`.
The compilation produces an error at the call to `nth_elements` on line 257 of `remove_outliers.h`.

I'm using a `std::vector<std::pair<Point_3, Vector3>>` and I get the following error with gcc: "error: no match for ‘operator<’ (operand types are ‘const CGAL::Vector_3<CGAL::Epick>’ and ‘const CGAL::Vector_3<CGAL::Epick>’)"
