### ISSUE TITLE
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/self_intersections.h does not compile

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1636]
Related to #1628. After the merge of that PR, the file no longer compile in isolation:
```
  /home/lrineau/Git/cgal/Installation/../Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/self_intersections.h:
  In member function ‘void CGAL::internal::Intersect_facets<TM, Kernel,
  Box, OutputIterator, VertexPointMap>::operator()(const Box*, const Box*)
  const’:

  /home/lrineau/Git/cgal/Installation/../Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/self_intersections.h:111:12:
  error: ‘coplanar’ is not a member of ‘CGAL’

           if(CGAL::coplanar(get(m_vpmap, target(h, m_tmesh)),
              ^~~~
  
  /home/lrineau/Git/cgal/Installation/../Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/self_intersections.h:115:12:
  error: ‘coplanar_orientation’ is not a member of ‘CGAL’

              CGAL::coplanar_orientation(get(m_vpmap, source(h, m_tmesh)),
              ^~~~
```

**Comment by MaelRL** [comment]
Added a commit to the PR itself.

**Comment by lrineau** [comment]
Oops! I thought that PR was already merged! I close this issue. Thanks.
