### ISSUE TITLE
Nested specialization syntax? 

### ISSUE THREAD

**Issue by Ahbee** [CGAL/cgal#274]
The parts where cgal wants to specialize [std::hash] (http://en.cppreference.com/w/cpp/utility/hash), dont compile for me on MAC OS like here. 

```c++
 template < class T>
  struct hash;

  template < class T, class Alloc >
  struct hash<CGAL::internal::In_place_list_iterator<T, Alloc> >
    : public std::unary_function<CGAL::internal::In_place_list_iterator<T, Alloc>, std::size_t>  {

    std::size_t operator()(const CGAL::internal::In_place_list_iterator<T, Alloc>& i) const
    {
      const T* ptr = &*i;
      return reinterpret_cast<std::size_t>(ptr)/ sizeof(T);
    }
  };

```
The error is
`Explicit specialization of non template struct 'hash'  `

**Comment by lrineau** [comment]
Cc @afabri

**Comment by lrineau** [comment]
@Ahbee, can you tell us more about which compiler you use, and which version?

**Comment by lrineau** [comment]
@Ahbee, that would be useful, too, if you gave us the full-compilation error, with its context (with the message such as `In file included from [...]` of `while compiling [something]`...).

**Comment by Ahbee** [comment]
This error from the polyhedron_prog_color example 
it is inside  <CGAL/In_place_list.h> which is included from <CGAL/HalfedgeDS_list.h> which is included from  <CGAL/HalfedgeDS_default.h> which is from   <CGAL/Polyhedron_3.h>.

Let me know if you need more , I am using default xCode compilers which is probably clang , but I tried gnu c++ ,but its the same error. I used cMake with xcode to build examples and CGAL. 
But I dont thing that is the correct syntax for specialization cause specializations always start like
```c++
template<>
Foo<specialtype>
```

**Comment by lrineau** [comment]
Then can you tell use more about the version of XCode you use? I will try to find out which compiler is shipped with it.

The syntax is a correct partial-specialization of a template class.

**Comment by lrineau** [comment]
I have tried the following code:
```C++
#include <functional>

namespace CGAL {
namespace internal {
template <typename T, typename A> class In_place_list_iterator;
}
}

namespace std {

template < class T>
struct hash;

template < class T, class Alloc >
struct hash<CGAL::internal::In_place_list_iterator<T, Alloc> >;

}
```
and it does compile with clang-3.5, using libstdc++ as the STL, in mode C++03 and C++11.

**Comment by Ahbee** [comment]
I have xcode 6.3.2 , and the code above does not compile for me? Same error 

` Explicit specialization of non template struct 'hash' ` I'll look more into it later

but I think my compiler is different than clang .  Apple LLVM?

**Comment by lrineau** [comment]
If you use XCode 6.3.2, then your compiler version is probably:
`Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)`

I'll try to test with that version.

**Comment by Ahbee** [comment]
i got it to compile by commenting out that forward declaring thing .
```c++
namespace CGAL {
    namespace internal {
        template <typename T, typename A> class In_place_list_iterator;
    }
}

namespace std {
    
//    template < class T>
//    struct hash;
    
    template < class T, class Alloc >
    struct hash<CGAL::internal::In_place_list_iterator<T, Alloc> >;
    
}
```

**Comment by mglisse** [comment]
http://stackoverflow.com/a/31597734/1918193

**Comment by lrineau** [comment]
Should be fixed with the pull-request #288, under testing tonight.

**Comment by lrineau** [comment]
Fixed by the merge 0fd6f2fa5951bee4775db456d2c25c79ef6db5e1 of #288.
