### PR TITLE
Polyhedron demo : Change the sizing preferency for DockWidgets

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

As it is quite hard to reproduce twice the same bug, I cannot be sure, but this seems to improve the dock widgets management.
## Release Management

* Affected package(s):Three

### CODE REVIEW

**Comment by lrineau** [comment]
[**@lrineau**](https://github.com/lrineau) commented on [Jun 12, 2018, 6:26 PM GMT+2](https://github.com/CGAL/cgal/pull/3165#issuecomment-396651537 "2018-06-12T16:26:52Z - Replied by Github Reply Comments"):
> Compilation error:

That is a conflict with #3144.

**Comment by lrineau** [comment]
[**@lrineau**](https://github.com/lrineau) commented on [Jun 12, 2018, 6:28 PM GMT+2](https://github.com/CGAL/cgal/pull/3165#issuecomment-396652074 "2018-06-12T16:28:32Z - Replied by Github Reply Comments"):
> [**@lrineau**](https://github.com/lrineau) commented on [Jun 12, 2018, 6:26 PM GMT+2](https://github.com/CGAL/cgal/pull/3165#issuecomment-396651537 "2018-06-12T16:26:52Z - Replied by Github Reply Comments"):
> > Compilation error:
> 
> That is a conflict with #3144.

Sorry. I did not test correctly. The compilation error is probably in #3144 itself.
