### ISSUE TITLE
examples/Surface_mesh/sm_do_intersect.cpp do not compile with Boost 1.65

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2493]
## Issue Details

It seems `boost::addressof<T>` is overloaded, in recent Boost (at least in 1.65.1), and that leads to a compilation error in `examples/Surface_mesh/sm_do_intersect.cpp`:

https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-I-54.shtml#Surface_mesh_Examples

## Environment

* CGAL version: was already in CGAL-4.11, maybe in CGAL-4.10 as well
* Boost version: 1.65.1
