### PR TITLE
Fix a compilation error in Travis

### PR DESCRIPTION
**Pull request by lrineau**
Fix an error introduced by the merge of #2198 in `master` and `releases/CGAL-4.10-branch`.

(fix the `check_pkg_Interpolation_headers` target)

* Affected package(s): all packages including `<CGAL/Triangulation_2.h>`
* Issue(s) solved (if any):
* Feature/Small Feature (if any):

### CODE REVIEW

**Comment by lrineau** [comment]
@sloriot That bug escaped the Travis checks, because #2198 was against `releases/CGAL-4.9-branch`, a branch that is not tested by Travis.
