### PR TITLE
Avoid std::size_t to FT conversion

### LINKED ISSUE #6308: GCC build error on Win64 (only) when using PMP::triangulate_faces w/ Gmp (regression in 5.3+)
## Issue Details

Compilation of a simple `triangulate_faces(Surface_mesh<Epeck>)` snippet (see full repro code below) fails to compile on Win64 w/ GCC since 5.3.1 (5.4 included; I couldn't test 5.3.0), but worked fine up to 5.2.4 / still works on Win32.

Using the mingw toolchain, same result either compiling in Windows itself w/ msys2 or cross-compiling from Linux w/ the mxe environment.

(Context: OpenSCAD is [adopting PMP corefinement and Suface_mesh](https://github.com/openscad/openscad/pull/4087)!)

Here's the error message:

```
In file included from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Number_types/internal/Exact_type_selector.h:25,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Exact_kernel_selector.h:26,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Filtered_kernel.h:22,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Exact_predicates_exact_constructions_kernel.h:21,
                 from bug.cc:2:
/mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Lazy_exact_nt.h: In instantiation of 'void CGAL::Lazy_exact_Cst<ET, X>::update_exact() const [with ET = __gmp_expr<__mpq_struct [1], __mpq_struct [1]>; X = long long unsigned int]':
/mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Lazy_exact_nt.h:152:8:   required from here
/mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Lazy_exact_nt.h:153:17: error: call of overloaded '__gmp_expr(const long long unsigned int&)' is ambiguous
  153 |     auto* pet = new typename Lazy_exact_nt_rep<ET>::Indirect(cste);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/is_convertible.h:23,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Rational_traits.h:23,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/number_type_basic.h:40,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/basic.h:28,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Cartesian/Cartesian_base.h:20,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Simple_cartesian.h:20,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Exact_predicates_exact_constructions_kernel.h:20,
                 from bug.cc:2:
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(double)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(float)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(long unsigned int)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(long int)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(short unsigned int)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(short int)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(unsigned int)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(int)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(unsigned char)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(signed char)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1648:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(__gmp_expr<__mpq_struct [1], __mpq_struct [1]>&&)'
 1648 |   __gmp_expr(__gmp_expr &&q)
      |   ^~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1642:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(const __gmp_expr<__mpq_struct [1], __mpq_struct [1]>&)'
 1642 |   __gmp_expr(const __gmp_expr &q)
      |   ^~~~~~~~~~
```

## Source Code

Here's how to reproduce the issue locally easily:

```bash
docker run --entrypoint=/bin/bash -it openscad/mxe-x86_64-openscad:cgal-5.4
```

```bash
export MXEDIR=/mxe
. scripts/setenv-mingw-xbuild.sh -64

echo '
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Polygon_mesh_processing/triangulate_faces.h>
#include <CGAL/Surface_mesh.h>

int main() {
	CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epeck>> mesh;
	CGAL::Polygon_mesh_processing::triangulate_faces(mesh);
}
'> bug.cc

/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.static.posix-g++ -std=c++14 \
	-I/mxe/usr/x86_64-w64-mingw32.static.posix/include \
	-DCGAL_USE_GMPXX=1 \
	-o bug.cc.obj -c bug.cc 
```

## Environment

* Operating system: Windows 64 bits (or Linux 64 bits w/ minwg cross-compiling env for Windows 64 bits)
* Compiler: x86_64-w64-mingw32.static.posix-g++ (GCC) 11.2.0
* Release or debug mode: unsure (both?)
* Specific flags used (if any): -DCGAL_USE_GMPXX=1
* CGAL version: 5.3.x, 5.4 (was working fine prior to that, e.g. 5.2.4)
* Boost version: 1_78
* Other libraries versions if used (Eigen, TBB, etc.): __GNU_MP__ 6.1.2

### PR DESCRIPTION
**Pull request by sloriot**
Fixes #6308

### CODE REVIEW

File: Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h [hunk 1]
```diff
@@ -1326,7 +1326,7 @@ triangulate_hole_polyline_with_cdt(const PointRange& points,
   }
 
   FT x = FT(0), y = FT(0), z = FT(0);
-  std::size_t num_normals = 0;
+  FT num_normals = 0;
```
Comment (lrineau) [inline Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h:1329]: `++num_normals` looks strange, for a floating-point type. But that seems valid, if not idiomatic.

Comment (mglisse) [reply Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h:1329]: Can num_normals grow large? If it can, with a lazy FT, it may create a deep tree which we know causes trouble during update_exact and destruction (I had experimented with avoiding the tree when the approximate interval turns out to be a point, but I don't think that ever led to a proper patch and PR). It it cannot, then we might as well use (`unsigned`) `long` or smaller for this counter, or keep size_t but convert it to that shorter type before the division.

**Review by mglisse — APPROVED** [review]
Thanks. Assuming we don't plan to support > 2G normals, this looks good.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.5-Ic-17
