### PR TITLE
Use property map in std::nth_element call

### LINKED ISSUE #5008: Compilation error when using `CGAL::remove_outliers` with `CGAL::named_parameters::point_map`
Looks like the changes introduced by commit https://github.com/CGAL/cgal/commit/82479e780bdaeb4c7257a3a1593f2e68e638d24e forbid the use of `CGAL::named_parameters::point_map` as a parameter of `CGAL::remove_outliers`.
The compilation produces an error at the call to `nth_elements` on line 257 of `remove_outliers.h`.

I'm using a `std::vector<std::pair<Point_3, Vector3>>` and I get the following error with gcc: "error: no match for ‘operator<’ (operand types are ‘const CGAL::Vector_3<CGAL::Epick>’ and ‘const CGAL::Vector_3<CGAL::Epick>’)"

### PR DESCRIPTION
**Pull request by sloriot**
Fixes #5008

### CODE REVIEW

File: Point_set_processing_3/include/CGAL/remove_outliers.h [hunk 1]
```diff
@@ -256,7 +256,11 @@ remove_outliers(
   {
     std::nth_element (f2r,
                       sorted_points.begin() + first_index_to_remove,
-                      sorted_points.end());
+                      sorted_points.end(),
+                      [&point_map](const std::pair<FT, value_type>& v1, const std::pair<FT, value_type>& v2)
+                      {
+                        return get(point_map, v1.second) < get(point_map, v2.second);
+                      });
```
Comment (sgiraudot) [inline Point_set_processing_3/include/CGAL/remove_outliers.h:263]: Actually the `nth_element` is supposed to be done on the computed distance, so it should `return v1.first < v2.second`. I don't understand how I did not see that this code was obviously wrong (on master) and did not detect errors with it before…

**Review by sgiraudot — APPROVED** [review]

**Comment by cjamin** [comment]
Thank you for the fix, it works!

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-18.shtml
