### PR TITLE
Polyhedron demo : OFF with colors

### PR DESCRIPTION
**Pull request by maxGimeno**
This is a fix for #119 
This PR:
- introduces a new scene_item : the Scene_surface_mesh_item. It is able to keep color data into its data structure (the surface_mesh), which allows it to store color information from a COFF or a classic OFF with color data on facets. No plugin is currently applicable on it, but it is destined to replace the Scene_polyhedron_item one day.
- modifies the Scene_polygon_soup_item to make it able to read color data from a (C)OFF and pass this data to the display.
- modifies the Orient_soup_plugin to add an action to convert a polygon_soup to a surface_mesh, and pass the color data to it.

### CODE REVIEW

**Comment by maxGimeno** [comment]
This has not been tested under Windows, as far as I know.

File: Stream_support/include/CGAL/IO/Scanner_OFF.h [hunk 1]
```diff
@@ -117,6 +117,8 @@ class I_Scanner_OFF_vertex_and_normals_iterator
             file_scan_vertex( *m_scan, m_current.first);
             if ( m_scan->has_normals())
                 file_scan_normal( *m_scan, m_current.second);
+            if ( m_scan->has_colors())
+             file_scan_color( *m_scan, Color);
             m_scan->skip_to_next_vertex( m_cnt);
```
Comment (lrineau) [inline Stream_support/include/CGAL/IO/Scanner_OFF.h]: ?! Can you explain? What is the variable `Color`?

File: Stream_support/include/CGAL/IO/File_scanner_OFF.h [hunk 2]
```diff
@@ -377,6 +536,71 @@ class CGAL_EXPORT File_scanner_OFF : public File_header_OFF {
...
+
+            } else {
+             CGAL::Color color = get_color_from_line(m_in);
+             r = color.red();
+             g = color.green();
+             b = color.blue();
+            }
+    }
+
   void skip_to_next_vertex( std::size_t current_vertex);
```
Comment (lrineau) [inline Stream_support/include/CGAL/IO/File_scanner_OFF.h]: The indentation is really strange. It should follow the indentation convention of the file.

File: Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+#include <boost/scoped_ptr.hpp>
+#include <boost/array.hpp>
+
+#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
+#include <CGAL/Surface_mesh/Surface_mesh_fwd.h>
+#include <CGAL/Surface_mesh/Surface_mesh.h>
+#include <QOpenGLShaderProgram>
+#include <QOpenGLBuffer>
+#include <boost/container/flat_map.hpp>
+
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h]: Should be included in the .cpp file only.

File: Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h [hunk 4]
```diff
@@ -0,0 +1,120 @@
...
+#include <CGAL/Three/Scene_item.h>
+#include <CGAL/Three/Viewer_interface.h>
+#include <vector>
+
+#include <boost/scoped_ptr.hpp>
+#include <boost/array.hpp>
+
+#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
+#include <CGAL/Surface_mesh/Surface_mesh_fwd.h>
+#include <CGAL/Surface_mesh/Surface_mesh.h>
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h]: Non-sense! If that file does not need the definition of the `Surface_mesh` then it should include the `fwd` header only, and let the `.cpp` file include the other header.

**Comment by lrineau** [comment]
TODO: @maxGimeno Please review the diff and fix it. There are too many things that should be improved.

File: Polyhedron/demo/Polyhedron/CMakeLists.txt [hunk 5]
```diff
@@ -254,6 +254,8 @@ if(CGAL_Qt5_FOUND AND Qt5_FOUND AND OPENGL_FOUND AND QGLVIEWER_FOUND)
   target_link_libraries(scene_polyhedron_selection_item scene_polyhedron_item_decorator scene_polyhedron_item_k_ring_selection)
 
   add_item(scene_polyhedron_shortest_path_item Plugins/Surface_mesh/Scene_polyhedron_shortest_path_item.cpp)
+
+  add_item(scene_surface_mesh_item Scene_surface_mesh_item.cpp)
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/CMakeLists.txt]: Why is the .cpp file in a sub-directory if the target has to be defined in this directory?

File: Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h [hunk 6]
```diff
@@ -45,6 +46,163 @@
 #include <CGAL/boost/graph/iterator.h>
 #include <CGAL/boost/graph/Euler_operations.h>
 
+inline CGAL::Color getIndexColor(int id)
+{
```
Comment (lrineau) [inline Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h]: There is already a copy of that function in another file!!

File: Stream_support/include/CGAL/IO/File_header_OFF.h [hunk 7]
```diff
@@ -85,7 +85,8 @@ class CGAL_EXPORT File_header_OFF : public File_header_extended_OFF {
     bool comments()           const { return ! m_no_comments; }
 
     std::size_t  index_offset()       const { return m_offset; }
-    bool has_colors()         const { return m_colors; } // COFF detected.
+    bool has_colors()          const { return m_colors; } // COFF detected.
```
Comment (lrineau) [inline Stream_support/include/CGAL/IO/File_header_OFF.h]: The diff seems useless, and breaks the existing indention.

File: Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h [hunk 8]
```diff
@@ -2502,49 +2660,171 @@ class Property_map
...
-        in.ignore((std::numeric_limits<std::streamsize>::max)(), '\n');
-      else
-        in.putback(c);
+      while(c == '#')
+      {
+       in.ignore((std::numeric_limits<std::streamsize>::max)(), '\n');
+       in >> c;
+      }
+      in.putback(c);
       return in;
```
Comment (lrineau) [inline Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h]: I do not understand. That function is supposed to skip the comment until the end of the line. What does it do, now, with that modification?

File: Polyhedron/demo/Polyhedron/CMakeLists.txt (hunk 5 above)
Comment (maxGimeno) [inline Polyhedron/demo/Polyhedron/CMakeLists.txt]: I don't know what you are talking about, the .h and .cpp both are in the root directory of the demo.

File: Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h (hunk 8 above)
Comment (maxGimeno) [inline Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h]: It skips all the lines until one that is not commented is found.

File: Polyhedron/demo/Polyhedron/CMakeLists.txt (hunk 5 above)
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/CMakeLists.txt]: You are right. I mixed it up with the line before:
```cmake
add_item(scene_polyhedron_shortest_path_item Plugins/Surface_mesh/Scene_polyhedron_shortest_path_item.cpp)
```
that does not depend on this PR.

File: Polyhedron/demo/Polyhedron/Plugins/IO/Surface_mesh_io_plugin.cpp [hunk 9]
```diff
@@ -0,0 +1,91 @@
...
+
+#include <QApplication>
+#include <QObject>
+#include <QAction>
+#include <QMainWindow>
+#include <QDebug>
+#include "Scene_surface_mesh_item.h"
+#include "Scene_polygon_soup_item.h"
+#include "Messages_interface.h"
+
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Plugins/IO/Surface_mesh_io_plugin.cpp]: I think that list of headers is too big.

* Why `<QApplication>`?
* Why `"messages_interface.h"`?

File: Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.h [hunk 10]
```diff
@@ -194,7 +205,7 @@ public Q_SLOTS:
     using CGAL::Three::Scene_item::initialize_buffers;
     void initialize_buffers(CGAL::Three::Viewer_interface *viewer) const;
     void compute_normals_and_vertices(void) const;
-    void triangulate_polygon(Polygons_iterator ) const;
+    void triangulate_polygon(Polygons_iterator , int nb) const;
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.h]: `nb` seems to be the ID of the polygon. If that is true, then the name of that parameter is really badly chosen! It should it something like `polygon_id` or `polygonID`.

File: Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp [hunk 11]
```diff
@@ -171,7 +209,7 @@ TDS,
 Itag>             CDTbase;
 typedef CGAL::Constrained_triangulation_plus_2<CDTbase>              CDT;
 void
-Scene_polygon_soup_item::triangulate_polygon(Polygons_iterator pit) const
+Scene_polygon_soup_item::triangulate_polygon(Polygons_iterator pit, int nb) const
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp]: Rename the parameter name `nb` here too.

File: Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp [hunk 12]
```diff
@@ -183,6 +221,7 @@ Scene_polygon_soup_item::triangulate_polygon(Polygons_iterator pit) const
     P_traits cdt_traits(normal);
 
     CDT cdt(cdt_traits);
+    QMap<CDT::Vertex_handle, int> p2p;
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp]: Here again the name `p2p` is surprising. Imaging you want to re-read your own code next year. What variable name, or comment, should you use/add to help understanding the code better?

File: Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h [hunk 13]
```diff
@@ -0,0 +1,117 @@
+#ifndef CGAL_SCENE_SURFACE_MESH_ITEM_H
+#define CGAL_SCENE_SURFACE_MESH_ITEM_H
+//Defines the precision of the positions (for performance/precision sake)
+#define GL_DATA GL_FLOAT
+#define gl_data float
+#define IS_FLOAT 1
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h]: In CGAL we have decided that macro names should start with `CGAL_`, to avoid naming conflicts with other libraries.

File: Stream_support/include/CGAL/IO/File_scanner_OFF.h [hunk 14]
```diff
@@ -35,6 +35,165 @@
 #include <CGAL/Point_3.h>
 #include <CGAL/Vector_3.h>
 
+
+inline CGAL::Color getIndexedColor(int id)
```
Comment (lrineau) [inline Stream_support/include/CGAL/IO/File_scanner_OFF.h]: This function name does not follow the naming rules of CGAL. As you are here modifying CGAL headers, and not Qt demos, there is no ambiguity: the naming convention is the convention of CGAL, and not the one of Qt.

Have a look at the developers manual: http://doc.cgal.org/latest/Manual/devman_code_format.html#secnaming_scheme

What is more, it is completely forbidden, to add a global function in the global namespace, in a CGAL header. That function would better be a private static function of the `File_scanner_OFF` class.

File: Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h [hunk 15]
```diff
@@ -2502,49 +2504,171 @@ class Property_map
...
   }
 /// @endcond
 
 
+  inline CGAL::Color get_color_from_line(std::istream &is)
```
Comment (lrineau) [inline Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h]: There is already a very similar function with the same name in `<CGAL/IO/File_scanner_OFF.h>`.

File: Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h [hunk 16]
```diff
@@ -44,6 +45,7 @@
 #include <CGAL/boost/graph/graph_traits_Surface_mesh.h>
 #include <CGAL/boost/graph/iterator.h>
 #include <CGAL/boost/graph/Euler_operations.h>
+#include <CGAL/IO/File_scanner_OFF.h>
```
Comment (lrineau) [inline Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h]: Why `#include <boost/fusion/container/map.hpp>` and `#include <CGAL/IO/File_scanner_OFF.h>`?

**Comment by lrineau** [comment]
The code is a lot better know, after the clean of commit https://github.com/CGAL/cgal/pull/1013/commits/5346143849c090e290c44d5732a485078e597668

But there are still room for improvements. I made comments in the diffs.

**Comment by lrineau** [comment]
I have a compilation error:
> Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp:17:63: fatal error: CGAL/Triangulation_2_filtered_projection_traits_3.h: No such file or directory

**Comment by lrineau** [comment]
... Actually, the compilation error was in `integration` only. There is a conflict with #875. @sloriot Should not #875 try to keep the compatibility with existing code? There might be other branches using the header you have removed.

**Comment by sloriot** [comment]
IIRC correctly I did not bother because these were undocumented headers.

**Comment by lrineau** [comment]
Unfortunately, that undocumented header is used in several branches outside `master`, mostly for the Polyhedron demo internals:
- `remotes/cgal-dev/Polyhedron_demo-OFF_with_color-GF`
- `remotes/cgal-dev/Scale_space_reconstruction_3_improve_nico`
- `remotes/cgal-dev/Polyhedron_demo-Euler_operations-GF`
- `remotes/cgal-dev/Polyhedron_demo-Path_selection-GF`
- `remotes/cgal-dev/Mesh_3-experimental-GF`
- `remotes/cgal-dev/Mesh_3-experimental_with_HOT-jtournoi`
- `remotes/cgal-dev/Segment_Delaunay_graph_2-make_it_faster-mkaravel`

The three later branches seems really old.

I also have a local branch that uses that file: `Polygon_mesh_processing-local_remeshing-GF`, but it is probably a merged branch whose history had been rebased. @janetournois, do you recognize that branch name?

**Comment by sloriot** [comment]
See #457

File: Polyhedron/demo/Polyhedron/Plugins/IO/Surface_mesh_io_plugin.cpp (hunk 9 above)
Comment (maxGimeno) [inline Polyhedron/demo/Polyhedron/Plugins/IO/Surface_mesh_io_plugin.cpp]: Messages_interface.h is needed to use messages_interface, which I do to notify the user when a file cannot be open or when the faces are not oriented correctly and a polygon_soup is loaded instead of a surface_mesh.

File: Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h (hunk 16 above)
Comment (maxGimeno) [inline Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h]: #include <CGAL/IO/File_scanner_OFF.h> is needed to acces the functions you made me delete from Surface-mesh.h because they were already in File_scanner_OFF.h.

**Comment by maxGimeno** [comment]
Cleaned-up

**Comment by lrineau** [comment]
@sloriot Once the PR is correctly tested in an internal release, please review the diff one last time before the merge in `master`.

**Comment by sloriot** [comment]
There are some [errors](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-35/Polyhedron_Demo/TestReport_lrineau_CentOS7-Release.gz) in the polyhedron demo that seems related to the get issues #1050 is trying to fix

**Comment by sloriot** [comment]
There are runtime errors with Surface_mesh on Windows. I guess there are due to this branch.

**Comment by maxGimeno** [comment]
I removed the binary file that I added by mistake. Hopefully the branch will work now.
