### PR TITLE
Polyhedron_demo: Use surface mesh item in Operations on polyhedra package

### LINKED ISSUE #1932: Polyhedron_demo: Use Scene_surface_mesh_item instead of Scene_polyhedron_item
## Issue Details

We should use the Scene_surface_mesh_item where it is possible, as it is more efficient in terms of memory consumption. We should integrate the plugins by package, to dispatch tests and to avoid a too important difference with the current master branch.

Packages:

- [x] AABB_tree
- [x] Convex_decomposition
- [x] Convex_hull
- [x] IO
- [x] Mesh_2
- [ ] Mesh_3
- [x] Operations_on_polyhedra
- [x] PCA
- [ ] PMP
- [ ] Point_set
- Subdivision_methods
- [ ] Surface_mesh
- [x] Surface_mesh_deformation

Plugins: 

- [x] Plugins/AABB_tree/Cut_plugin.cpp
- [x]  Plugins/PCA/Create_bbox_mesh_plugin.cpp
- [x]  Plugins/PCA/Pca_plugin.cpp
- [x]  Plugins/PCA/Scene_polyhedron_transform_item.h
- [x]  Plugins/PCA/Edit_box_plugin.cpp
- [x]  Plugins/Mesh_3/Detect_sharp_edges_plugin.cpp
- [ ]  Plugins/Mesh_3/Optimization_plugin_cgal_code.cpp
- [x]  Plugins/Mesh_3/Mesh_3_plugin.cpp
- [x]  Plugins/IO/GOCAD_io_plugin.cpp
- [x]  Plugins/IO/Surf_io_plugin.cpp
- [x]  Plugins/IO/STL_io_plugin.cpp
- [x]  Plugins/IO/VTK_io_plugin.cpp
- [x]  Plugins/Convex_decomposition/Nef_plugin.cpp
- [x]  Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp
- [x]  Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.h
- [ ]  Plugins/Point_set/Surface_reconstruction_plugin.cpp #Uses a Polyhedron_incremental_builder_3
- [x]  Plugins/Point_set/Point_set_shape_detection_plugin.cpp
- Plugins/Surface_mesh/Remeshing_plugin.cpp # Must enhance Mesh_3 and then remove this plugin
- [x]  Plugins/Surface_mesh/Mesh_simplification_plugin.cpp
- [ ]  Plugins/Surface_mesh/Mesh_segmentation_plugin.cpp 
- [x]  Plugins/Surface_mesh/Shortest_path_plugin.cpp
-  Plugins/Surface_mesh/Remeshing_plugin_cgal_code.cpp # Must enhance Mesh_3 and then remove this plugin
-  Plugins/Surface_mesh/Parameterization_plugin.cpp#There is an on going SF concerning this plugin
- [x]  Plugins/Convex_hull/Convex_hull_plugin.cpp
- [x]  Plugins/Convex_hull/Kernel_plugin.cpp
- [x]  Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp
- [x]  Plugins/Operations_on_polyhedra/Point_set_from_vertices_plugin.cpp
- [x]  Plugins/PMP/Inside_out_plugin.cpp
- [x]  Plugins/PMP/Point_inside_polyhedron_plugin.cpp
- [x]  Plugins/PMP/Polyhedron_slicer_plugin.cpp
- [x]  Plugins/PMP/Corefinement_plugin.cpp
- [x]  Plugins/PMP/Polyhedron_stitching_plugin.cpp
- [x]  Plugins/PMP/Repair_polyhedron_plugin.cpp
- [x]  Plugins/PMP/Surface_intersection_plugin.cpp
- [x]  Plugins/PMP/Distance_plugin.cpp
- [x]  Plugins/PMP/Selection_plugin.cpp
- [x]  Plugins/PMP/Join_and_split_polyhedra_plugin.cpp
- [x]  Plugins/PMP/Hole_filling_polyline_plugin.cpp
- [x]  Plugins/PMP/Hole_filling_plugin.cpp # TODO check normalize_borders
- [x]  Plugins/PMP/Jet_fitting_plugin.cpp
- [x]  Plugins/PMP/Isotropic_remeshing_plugin.cpp
- [ ]  Plugins/PMP/Mean_curvature_flow_skeleton_plugin.cpp
- [x]  Plugins/PMP/Triangulate_facets_plugin.cpp
- [x]  Plugins/Mesh_2/Mesh_2_plugin.cpp
-  Plugins/Subdivision_methods/Subdivision_methods_plugin.cpp #There is an on going SF concerning this plugin

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
The plugins in Operations on Polyhedra are now able to work on a Scene_surface_mesh_item as well as on a Scene_polyhedron_item.

This PR depends on #1954 and #1983.
## Release Management

* Affected package(s):Polyhedron_demo
* Issue(s) solved (if any): fix #1932

### CODE REVIEW

File: Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp [hunk 1]
```diff
@@ -173,58 +175,112 @@ public Q_SLOTS:
...
       //apply the clipping function
-      Q_FOREACH(Scene_polyhedron_item* poly, polyhedra)
+      Q_FOREACH(Scene_item* item, polyhedra)
       {
+        Scene_surface_mesh_item *sm_item = qobject_cast<Scene_surface_mesh_item*>(item);
+        Scene_polyhedron_item* poly_item = NULL;
+        if(!sm_item)
+        {
+          poly_item = qobject_cast<Scene_polyhedron_item*>(item);
+        }
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp]: This could be simplified to:
```C++
Scene_surface_mesh_item* sm_item = qobject_cast<Scene_surface_mesh_item*>(item);
Scene_polyhedron_item* poly_item = qobject_cast<Scene_polyhedron_item*>(item);
```
One of `sm_item`/`poly_item` will be null, and the other will be non-null.

**Comment by lrineau** [comment]
It does not compile, according to Travis: https://travis-ci.org/CGAL/cgal/jobs/207039415

**Comment by maxGimeno** [comment]
This is not the right version, and yet I cannot push. I think something went wrong in the tree after I rebased too many times or something. I'll try to force it with a dummy commit.

**Comment by lrineau** [comment]
That PS was tested last night. Compilation errors:
```
test\Polyhedron_Demo\Scene_points_with_normal_item.cpp(66) : error C2899: typename cannot be used outside a template declaration
test\Polyhedron_Demo\Scene_points_with_normal_item.cpp(71) : error C2899: typename cannot be used outside a template declaration

```
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.11-Ic-29/Polyhedron_Demo/TestReport_afabri_x64_Cygwin-Windows8_MSVC2013-Release-32bits.gz

**Comment by maxGimeno** [comment]
Ready for testing.

**Comment by lrineau** [comment]
@maxGimeno: This PR conflicts with #2213. Please merge this PR #1941 in `integration` today.

**Comment by maxGimeno** [comment]
done
