### PR TITLE
BGL new helper functions and Polyhedron_demo's Basic_volume_generator_plugin

### LINKED ISSUE #2036: Polyhedron_demo : basic volumes generator
## Issue Details
Feature request : 
Add a cube/cylinder/sphere/tetrahedron generator and then be able to transform the results to adapt the size, orientation and position (using the affine_transformation_plugin).

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
This PR adds new helper functions in BGL and a plugin in the Plugins/PCA directory that generates a basic cube, sphere, cylinder or tetrahedron, all inscribed in a cube centered on (0,0,0) and with a side of 1. It is possible to use the affine_transformation_plugin to reshape them with some scaling or change their position and orientation.
## Release Management

* Affected package(s):Polyhedron_demo
* Issue(s) solved (if any): fix #2036
* Feature/Small Feature (if any): [here](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Basic_volumes_generator)

### CODE REVIEW

**Comment by afabri** [comment]
The implementation is not how it should be done. We have functions such as [`make_tetrahedron()`](http://doc.cgal.org/latest/BGL/group__PkgBGLHelperFct.html#gad2e132763721d8e4fd22020c1665c15f) in CGAL, and if something like `make_sphere()` or `make_cylinder()`   (or should it be `make_polyhedral_XX()` is missing we should add it to the package and not just inside a plugin.

**Comment by maxGimeno** [comment]
You asked for a plugin, not new BGL functions. Besides, a sphere and a cylinder are not possible to create, all we can do are approximations. Do we want functions to create approximative volumes in BGL ?

**Comment by afabri** [comment]
Cylinder: Instead of precision being an integer and then the plugin computing the angle 360/precision, I would expect to enter an angle.

Sphere: The requirement "must divide 360 and 180" (btw., the latter implies the former) must be checked or enforced as otherwise you generate a slab that is wider.
Also for the sphere  it is probably interesting to produce a mesh with more [uniform triangles](http://area.autodesk.com/blogs/the-maya-blog/creating_a_sphere_with_very_uniform_triangles). I will look for better algorithms.

**Comment by maxGimeno** [comment]
https://gamedevdaily.io/four-ways-to-create-a-mesh-for-a-sphere-d7956b825db4

 I guess the one you have in mind is the last one, the icosahedron, which seems to be the same as the mesh in Sphere.off in our data ?

**Comment by afabri** [comment]
Here comes another feature request:  A grid generator. I specify lower left and upper right in x,y, as well as the number of cells in x and y direction, and it generates a face graph in the z=0 plane, either with quads, or triangles (quad with the diagonal in direction 0,0 to 1,1/).

**Comment by lrineau** [comment]
There are multiple warnings on Windows:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.11-Ic-22/BGL/TestReport_afabri_x64_Cygwin-Windows8_MSVC2012-Debug-64bits.gz

**Comment by lrineau** [comment]
1. the warnings (see https://github.com/CGAL/cgal/pull/2068#issuecomment-303329260),
2. the new plugin should be added to the `cgal_test` script,
3. there is a compilation error, due to a breaking change from PR https://github.com/CGAL/cgal/pull/1921 (Cc @MaelRL @afabri):

```
[ 57%] Building CXX object Plugins/PCA/CMakeFiles/basic_generator_plugin.dir/Basic_generator_plugin.cpp.o
cd /home/cgal_tester/build/src/cmake/platforms/ArchLinux-clang-CXX1z/test/Polyhedron_Demo/Plugins/PCA && /bin/clang++  -DCGAL_EIGEN3_ENABLED -DCGAL_TEST_SUITE -DCGAL_USE_GMP -DCGAL_USE_MPFR -DCGAL_USE_ZLIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_KEYWORDS -DQT_OPENGL_LIB -DQT_SCRIPT_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DSCENE_IMAGE_GL_BUFFERS_AVAILABLE -DUSE_FORWARD_DECL -Dbasic_generator_plugin_EXPORTS -I/home/cgal_tester/build/src/cmake/platforms/ArchLinux-clang-CXX1z/test/Polyhedron_Demo/Plugins/PCA -I/home/cgal_tester/build/src/cmake/platforms/ArchLinux-clang-CXX1z/test/Polyhedron_Demo/Plugins/PCA/basic_generator_plugin_autogen/include -I/home/cgal_tester/build/src/cmake/platforms/ArchLinux-clang-CXX1z/test/Polyhedron_Demo/./CGAL_demo -I/home/cgal_tester/build/src/cmake/platforms/ArchLinux-clang-CXX1z/test/Polyhedron_Demo/../../include -I/home/cgal_tester/build/src/cmake/platforms/ArchLinux-clang-CXX1z/test/Polyhedron_Demo/./include -I/home/cgal_tester/build/src/cmake/platforms/ArchLinux-clang-CXX1z/test/Polyhedron_Demo/. -I/home/cgal_tester/build/src/cmake/platforms/ArchLinux-clang-CXX1z/test/Polyhedron_Demo -I/home/cgal_tester/build/src/cmake/platforms/ArchLinux-clang-CXX1z/include -I/mnt/testsuite/include -isystem /usr/include/eigen3 -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -isystem /usr/include/qt/QtScript -isystem /usr/include/qt/QtOpenGL -isystem /usr/include/qt/QtXml  -Wall -std=c++1z -g -fPIC   -fPIC -std=gnu++11 -o CMakeFiles/basic_generator_plugin.dir/Basic_generator_plugin.cpp.o -c /home/cgal_tester/build/src/cmake/platforms/ArchLinux-clang-CXX1z/test/Polyhedron_Demo/Plugins/PCA/Basic_generator_plugin.cpp
/home/cgal_tester/build/src/cmake/platforms/ArchLinux-clang-CXX1z/test/Polyhedron_Demo/Plugins/PCA/Basic_generator_plugin.cpp:14:10: fatal error: 'CGAL/Subdivision_method_3.h' file not found
#include <CGAL/Subdivision_method_3.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by afabri** [comment]
Once Subdivision_facegraph is merged into master, the plugin should lowecase the header file name.

**Comment by lrineau** [comment]
The PR #1921, about Subdivision_facegraph, is now merged in `master`. You can rebase this one, to fix the compilation error. See the comment from Andreas (https://github.com/CGAL/cgal/pull/2068#issuecomment-303342126) answering mine (https://github.com/CGAL/cgal/pull/2068#issuecomment-303330554).

**Comment by maxGimeno** [comment]
The errors in todays testsuite in BGL test_helpers come from here.

**Comment by lrineau** [comment]
There is a Doxygen warning:
```
citelist:4: Warning: Unexpected new line character
/home/cgal-testsuite/cgal_doc_build/CGAL-4.11-Ic-31/include/CGAL/boost/graph/helpers.h:1009: Warning: The following parameters of CGAL::make_grid(typename boost::graph_traits< Graph >::vertices_size_type i, typename boost::graph_traits< Graph >::vertices_size_type j, Graph &g, const CoordinateFunctor &calculator, bool triangulated=false) are not documented:
  parameter 'i'
  parameter 'j'
```
https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.11-Ic-31/BGL.log

**Comment by lrineau** [comment]
Warning on Windows:
```
```

**Comment by lrineau** [comment]
[Warning on Windows][*]:
```
[100%] Building CXX object Plugins/PCA/CMakeFiles/basic_generator_plugin.dir/Basic_generator_plugin.cpp.obj
	cd E:\CGAL\test\CGAL-4.11-Ic-34\cmake\platforms\x64_Cygwin-Windows10_MSVC2015-Release-64bits\test\Polyhedron_Demo\Plugins\PCA
	C:\PROGRA~2\MICROS~3.0\VC\bin\amd64\cl.exe  @C:\Users\Jane\AppData\Local\Temp\nmDF7.tmp
Basic_generator_plugin.cpp
E:\CGAL\test\CGAL-4.11-Ic-34\cmake\platforms\x64_Cygwin-Windows10_MSVC2015-Release-64bits\test\Polyhedron_Demo\Plugins\PCA\Basic_generator_plugin.cpp(707): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
E:\CGAL\test\CGAL-4.11-Ic-34\cmake\platforms\x64_Cygwin-Windows10_MSVC2015-Release-64bits\test\Polyhedron_Demo\Plugins\PCA\Basic_generator_plugin.cpp(240): note: see reference to function template instantiation 'void Basic_generator_plugin::generateGrid<Scene_surface_mesh_item>(void)' being compiled
```

  [*]: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.11-Ic-34/Polyhedron_Demo/TestReport_jtournois_x64_Cygwin-Windows10_MSVC2015-Release-64bits.gz

**Comment by maxGimeno** [comment]
Just fixed it, I think.

**Comment by lrineau** [comment]
I have tried this branch before merging it in `master`, because nobody had reviewed it so far, and I am not completely convinced.

## Problems
1. The features "Add polyline" is now hidden deep in the Operation menu, as "Basic Generation>Basic Generator", and then the "polyline" tab is hidden at the end of the tab widgets, and we may not see it.

2. The name "Basic Generation>Basic Generator" is... well, not a good one.

3. The [image for prisme][pr] and the [image for pyramid][py] are far too complicated and useless: no need to specify the points P0, P1, ... Pn, because the user interface does not allow to modify them. That is different from the tetrahedron or the hexahedron.
  - prisme: ![prisme][pr]... Anyway I cannot understand anything from that picture.
  - pyramid: ![pyramid][py]... The picture is strange, useless, and it is strangely aliased.

  [py]: https://raw.githubusercontent.com/maxGimeno/cgal/421b488883f82f81b5d2a71c256b29f79902409b/Polyhedron/demo/Polyhedron/resources/base.png
  [pr]: https://raw.githubusercontent.com/maxGimeno/cgal/421b488883f82f81b5d2a71c256b29f79902409b/Polyhedron/demo/Polyhedron/resources/prism.png

4. The [image for a sphere][sp] is also no the right one, and it is wrong! Just show the sphere with the default precision. The image is wrong because the subdivision step is wrong on the image: the brown edge can stay in the mesh...
  - sphere: ![sphere][sp]

  [sp]: https://raw.githubusercontent.com/maxGimeno/cgal/421b488883f82f81b5d2a71c256b29f79902409b/Polyhedron/demo/Polyhedron/resources/icosphere.png

## Proposal
I suggest:
  - fix the images,
  - remove the action from the Operation menu,
  - add a submenu in File, where there was previously "Add polylines..." and "Add point set...", name it "Add basic objects", and in that submenu, add as many action as there are object types: "Add point set...", "Add polylines...", "Add sphere...", "Add hexahedron..." and so on. The various action would:
    - make sure the dock widget is shown,
    - and switch the tab widget to the right tab.

**Comment by lrineau** [comment]
This PR has a little conflict with `master`, but also a conflicts with #1961 (selected for `integration` tonight). I will delay its testing.

**Comment by lrineau** [comment]
In addition to the issues reported in y last comment (https://github.com/CGAL/cgal/pull/2068#issuecomment-310392543) there is an error in Travis in the polyhedron demo:
```
[ 20%] Generating qrc_File.cpp
make[2]: *** No rule to make target `../resources/base.png', needed by `qrc_Polyhedron_3.cpp'.  Stop.
```
https://travis-ci.org/CGAL/cgal/jobs/245711205#L5315
