### ISSUE TITLE
Epick issue: cannot call CGAL::squared_radius using ADL

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#129]
We cannot call `CGAL::squared_radius` on `CGAL::Point_3<Epick>` using ADL.
```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>

namespace CGAL {

void f() {
  CGAL::Point_3<CGAL::Epick> a, b, c, d;
  squared_radius(a, b, c, d);
}

} // end namespace CGAL


int main(int argc, char* argv[])
{
  CGAL::f();
}
```
The Apple clang compiler 6.0 (based on clang 3.5) [reports a substitution error](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-Ic-61/Advancing_front_surface_reconstruction_Examples/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.0_Release.gz):
```
/Users/cgaltester/cgal_test/CGAL-4.7-Ic-61/include/CGAL/Kernel/global_functions_internal_3.h:897:13: error: 'FT' is a private member of 'CGAL::Point_3<CGAL::Epick>'
typename K::FT
            ^
/Users/cgaltester/cgal_test/CGAL-4.7-Ic-61/include/CGAL/Advancing_front_surface_reconstruction.h:1115:27: note: while substituting deduced template arguments into function template 'squared_radius' [with K = CGAL::Point_3<CGAL::Epick>]
                  value = squared_radius(pp0, pp1, pp2, pp3);
                          ^
```

As far as I understand, the compiler is right: `CGAL::Epick` derives indirectly from:
```
CGAL::internal::Static_filters<CGAL::Filtered_kernel_base<CGAL::Type_equality_wrapper< CGAL::Simple_cartesian<double>::Base<Epick>::Type, CGAL::Epick> > > 
```
then `CGAL::internal` is in the *associated set of namespaces* of the unqualified lookup (see [ADL on cppreference.com](http://en.cppreference.com/w/cpp/language/adl)). And the following substitution:
```
template < class K >
inline
typename K::FT
squared_radius(const typename K::Point_3 &p,
               const typename K::Point_3 &q,
               const typename K::Point_3 &r, const K &k)
{
  return k.compute_squared_radius_3_object()(p, q, r);
}
```
with `K = CGAL::Point_3<CGAL::Epick>`, gives a hard error. [SFINAE](http://en.cppreference.com/w/cpp/language/sfinae) does not apply, because `CGAL::Point_3<CGAL::Epick>::FT` does exist: the error is that `CGAL::Point_3<CGAL::Epick>::FT` is private. Would it be public, I think that SFINAE would apply to the remaining errors when looking for ` K::Point_3` (that is `CGAL::Point_3<CGAL::Epick>::Point_3`), because "attempting to use a member of a type, where the type does not contain the specified member " is an SFINAE error.

**Comment by lrineau** [comment]
See [CGAL programming conventions](http://doc.cgal.org/latest/Manual/devman_code_format.html#secprogramming_conventions):
> Do not give private types or typedefs a name likely to be used as a public interface by an other class, e.g. prefer `Point_3_` to `Point_3` (in general, add an underscore as suffix). The reason for this convention is that SFINAE does not extend to access control (meaning that the existence of a private type can break overloading for other classes).

**Comment by lrineau** [comment]
Actually, even in the files where the manual is cited, the recommandation is not followed:
```c++
renoir ~/Git/cgal $ ack -C 3 -Q 'http://doc.cgal.org/latest/Manual/devman_code_format.html' */include/ 
Cartesian_kernel/include/CGAL/Cartesian/Vector_3.h
34-template < class R_ >
35-class VectorC3
36-{
37:// http://doc.cgal.org/latest/Manual/devman_code_format.html#secprogramming_conventions
38-  typedef typename R_::FT                   FT_;
39-  typedef typename R_::Point_3              Point_3;
40-  typedef typename R_::Vector_3             Vector_3;

Cartesian_kernel/include/CGAL/Cartesian/Point_2.h
34-{
35-  typedef PointC2<R_>                       Self;
36-  typedef typename R_::FT                   FT;
37:// http://doc.cgal.org/latest/Manual/devman_code_format.html#secprogramming_conventions
38-  typedef typename R_::Vector_2             Vector_2_;
39-  typedef typename R_::Point_2              Point_2;
40-

Cartesian_kernel/include/CGAL/Cartesian/Sphere_3.h
36-class SphereC3
37-{
38-  typedef typename R_::FT                   FT;
39:// http://doc.cgal.org/latest/Manual/devman_code_format.html#secprogramming_conventions
40-  typedef typename R_::Point_3              Point_3_;
41-  typedef typename R_::Vector_3             Vector_3;
42-  typedef typename R_::Sphere_3             Sphere_3;

Kernel_23/include/CGAL/Vector_3.h
39-class Vector_3 : public R_::Kernel_base::Vector_3
40-{
41-  typedef typename R_::RT                    RT;
42:// http://doc.cgal.org/latest/Manual/devman_code_format.html#secprogramming_conventions
43-  typedef typename R_::FT                    FT_;
44-  typedef typename R_::Segment_3             Segment_3;
45-  typedef typename R_::Ray_3                 Ray_3;

Kernel_23/include/CGAL/Sphere_3.h
38-class Sphere_3 : public R_::Kernel_base::Sphere_3
39-{
40-  typedef typename R_::FT                    FT;
41:// http://doc.cgal.org/latest/Manual/devman_code_format.html#secprogramming_conventions
42-  typedef typename R_::Point_3               Point_3_;
43-  typedef typename R_::Circle_3              Circle_3;
44-  typedef typename R_::Aff_transformation_3  Aff_transformation_3;
```

**Comment by lrineau** [comment]
TODO: this bug is probably fixed, at least for `squared_radius`.

**Comment by sloriot** [comment]
Your test program does not compile with Clang 3.3.0

**Comment by lrineau** [comment]
@bo0ts Can you have a look at this bug, after you have finished with #143?

**Comment by bo0ts** [comment]
The test-program fails to compile on clang 3.6.2 without any special options, but compiles with `--std=c++11`.

Access violations can error in an SFINAE fashion in C++11 and I suspect that clang (correctly) does not allow in C++03 mode, while gcc is not so strict about it.

**Comment by lrineau** [comment]
I confirm that even with clang-3.5, the [code you gave](https://github.com/CGAL/cgal/issues/129#issuecomment-128295483) compiles with `-std=c++11` but not without:
```
In file included from /home/lrineau/tmp/test/essai.cpp:1:
In file included from /home/lrineau/Git/cgal/Kernel_23/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:28:
In file included from /home/lrineau/Git/cgal/Cartesian_kernel/include/CGAL/Simple_cartesian.h:28:
In file included from /home/lrineau/Git/cgal/Cartesian_kernel/include/CGAL/Cartesian/Cartesian_base.h:30:
In file included from /home/lrineau/Git/cgal/Kernel_23/include/CGAL/Kernel/global_functions.h:32:
In file included from /home/lrineau/Git/cgal/Kernel_23/include/CGAL/Kernel/global_functions_3.h:29:
/home/lrineau/Git/cgal/Kernel_23/include/CGAL/Kernel/global_functions_internal_3.h:897:13: error: 'FT' is a private member of
      'CGAL::Point_3<CGAL::Epick>'
typename K::FT
            ^
/home/lrineau/tmp/test/essai.cpp:6:3: note: while substituting deduced template arguments into function template 'squared_radius'
      [with K = CGAL::Point_3<CGAL::Epick>]
  squared_radius(a, b, c, d);
  ^
```

**Comment by bo0ts** [comment]
PR #256 should fix the issue, but in the long term we want to improve namespace hygiene.

**Comment by lrineau** [comment]
Philipp (@bo0ts): please write an issue with the description of the long-term solution, and add a topic for next developers meeting (end of Sept. 2015 at Nancy) about that issue.
