### PR TITLE
Polyhedron_demo: Items use d-pointers

### LINKED ISSUE #855: Kernel computation in the Polyhdron_3 demo seems not to work
The kernel of a polyhdron P is the volume visible from all faces of P.   
It seems not to work in master. It seems not to work in 4.7.1 either. 
It has no API, but is just some code using the QP_Solver in the kernel_plugin.

Either we fix it ( Hello author: @palliez), or we simply remove it.

### PR DESCRIPTION
**Pull request by maxGimeno**
This PR makes the binary compatibility of the Polyhedron_demo more robust by using d-pointers for every item.

The concept is to use a friend protected struct declared in the .h but defined entirely in the .cpp, that will hold all of the private data of the item. This way, the .h is rarely modified, as it only holds the public API.

It also fixes #855 (commit cd56708)

### CODE REVIEW

**Comment by sloriot** [comment]
I have the following errors when trying to compile:
```
/home/sloriot/CGAL/git/integration/Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp:31:10: error: ‘Facets’ was not declared in this scope
     vaos[Facets]->bind();
          ^
/home/sloriot/CGAL/git/integration/Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp:32:5: error: ‘program’ was not declared in this scope
     program = getShaderProgram(PROGRAM_PLANE_TWO_FACES);
     ^
/home/sloriot/CGAL/git/integration/Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp:36:35: error: ‘frame’ was not declared in this scope
       f_matrix.data()[i] = (float)frame->matrix()[i];
                                   ^
/home/sloriot/CGAL/git/integration/Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp:50:64: error: ‘positions_quad’ was not declared in this scope
     viewer->glDrawArrays(GL_TRIANGLES, 0, static_cast<GLsizei>(positions_quad.size()/3));
                                                                ^
/home/sloriot/CGAL/git/integration/Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp: In member function ‘void Scene_clipping_plane_item::initializeBuffers(CGAL::Three::Viewer_interface*) const’:
/home/sloriot/CGAL/git/integration/Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp:59:5: error: ‘program’ was not declared in this scope
     program = getShaderProgram(PROGRAM_PLANE_TWO_FACES, viewer);
     ^
/home/sloriot/CGAL/git/integration/Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp:61:10: error: ‘Facets’ was not declared in this scope
     vaos[Facets]->bind();
          ^
/home/sloriot/CGAL/git/integration/Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp:63:13: error: ‘Facets_vertices’ was not declared in this scope
     buffers[Facets_vertices].bind();
             ^
/home/sloriot/CGAL/git/integration/Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp:64:39: error: ‘positions_quad’ was not declared in this scope
     buffers[Facets_vertices].allocate(positions_quad.data(),
                                       ^
/home/sloriot/CGAL/git/integration/Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp:72:10: error: ‘Edges’ was not declared in this scope
```

**Comment by sloriot** [comment]
I now have the following error:
`/home/sloriot/CGAL/git/integration/Polyhedron/demo/Polyhedron/Plugins/IO/STL_io_plugin.cpp:78: undefined reference to `void Scene_polygon_soup_item::load<boost::array<double, 3ul>, boost::array<int, 3ul> >(std::vector<boost::array<double, 3ul>, std::allocator<boost::array<double, 3ul> > > const&, std::vector<boost::array<int, 3ul>, std::allocator<boost::array<int, 3ul> > > const&)'
`

**Comment by sloriot** [comment]
There are more errors/warning related to extra typename

**Comment by sloriot** [comment]
Testsuite is good now
