### ISSUE TITLE
Some combinations of intersections of circular kernel objest fail to compile

### ISSUE THREAD

**Issue by efifogel** [CGAL/cgal#1717]
The following combinations fail: Line_2, Line_2, Line_arc_2, Circular_arc_2, and Circular_arc_2, Line_arc_2.
The attached source can be used to reproduce the problems.

[intersecting_arcs.cpp.zip](https://github.com/CGAL/cgal/files/611012/intersecting_arcs.cpp.zip)

**Comment by afabri** [comment]
What do you expect as coordinates for a default constructed point. And if their coordinates were 0, what do you expect a `CGAL::Line_2` to be when it is constructed from two points at the origin?
Should we add a precondition to the line constructor that the two points must be different?

**Comment by afabri** [comment]
@efifogel PING

**Comment by efifogel** [comment]
They fail to compile...
The test case in the attached archive has all the failing combinations commented out.

**Comment by afabri** [comment]
Efi, please fill in your three points.  This does not compile on the  compiler XXX, in the branch YYY,.  in release/debug,...

**Comment by efifogel** [comment]
This does not compile on g++ 4.8.4, using branch master, in release.

**Comment by sgiraudot** [comment]
I tried to modify a bit the code to plainly satisfy to the [reference manual](file:///home/simon/CGAL/master/build/release/doc_output/Kernel_23/group__intersection__circular__grp.html) and to be as explicit as possible (no automatic template deduction):

```c++
  typedef typename CGAL::cpp11::result_of<Circular_k::Intersect_2(Line_2, Line_2)>::type
    Intersection_result;
  std::vector<Intersection_result> res;
  CGAL::intersection<Line_2, Line_2, std::back_insert_iterator<std::vector<Intersection_result> > >(line, line, std::back_inserter(res));
```

It still doesn't compile but the error is different. It seems that the right version of `CGAL::intersection()` is never found, I have this kind of error:

```
note:   template argument deduction/substitution failed:
/home/simon/CGAL/My_tests/intersecting_arcs.cpp:25:136: error: wrong number of template arguments (3, should be 1)
   CGAL::intersection<Line_2, Line_2, std::back_insert_iterator<std::vector<Intersection_result> > >(line, line, std::back_inserter(res));
```

Even if I add explicitly `#include <CGAL/Circular_kernel_intersections.h>`, same error...

**Comment by sloriot** [comment]
@efifogel  That was indeed a bug.
