### ISSUE TITLE
Visibility Polygon occasional bad_object_cast error

### ISSUE THREAD

**Issue by BurakHocaoglu** [CGAL/cgal#5694]
Hello there,

I've been using CGAL in a distributed swarm simulation application with ROS to enable disjoint processes to communicate with each other. I have an issue of occasional errors in visibility polygon computation in general case (i.e. environment with holes), which takes place periodically at some frequency - when the agent moves, the visibility would potentially be changed.

## Issue Details

While coding, I looked at the example ```general_polygon_example.cpp```, but changed the exact kernel to inexact and copied the similar part in ```simple_polygon_visibility.cpp``` to generate visibility inside of the polygon, instead of only from outer boundary. The example worked with inexact kernel, but in my simulation application, I get runtime errors from processes. I've added one of the cases that generates errors in the example source code:

```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Triangular_expansion_visibility_2.h>
#include <CGAL/Arr_segment_traits_2.h>
#include <CGAL/Arrangement_2.h>
#include <CGAL/Arr_naive_point_location.h>
#include <CGAL/draw_polygon_2.h>
#include <CGAL/Polygon_2.h>
#include <iostream>
#include <vector>

typedef CGAL::Exact_predicates_inexact_constructions_kernel     Kernel;
typedef Kernel::Point_2                                         Point_2;
typedef Kernel::Segment_2                                       Segment_2;
typedef CGAL::Polygon_2<Kernel>                                 Polygon_2;
typedef CGAL::Arr_segment_traits_2<Kernel>                      Traits_2;
typedef CGAL::Arrangement_2<Traits_2>                           Arrangement_2;
typedef Arrangement_2::Halfedge_const_handle                    Halfedge_const_handle;
typedef Arrangement_2::Face_handle                              Face_handle;

typedef CGAL::Triangular_expansion_visibility_2<Arrangement_2>  TEV;

int main() {
	Point_2 p1(-60., 50.), p2(-60., -40.), p3(50., -40.), p4(50., 50.);

	Point_2 h11(-20., 10.), h12(10., -20.), h13(-10., -30.), h14(-40., 10.);
	Point_2 h21(-20., 40.), h22(0., 30.), h23(0., 20.), h24(-40., 30.);
	Point_2 h31(-40., -10.), h32(-30., -30.), h33(-50., -20.), h34(-50., -10.);

	std::vector<Segment_2> segments;
	segments.push_back(Segment_2(p1, p2));
	segments.push_back(Segment_2(p2, p3));
	segments.push_back(Segment_2(p3, p4));
	segments.push_back(Segment_2(p4, p1));

	segments.push_back(Segment_2(h11, h12));
	segments.push_back(Segment_2(h12, h13));
	segments.push_back(Segment_2(h13, h14));
	segments.push_back(Segment_2(h14, h11));

	segments.push_back(Segment_2(h21, h22));
	segments.push_back(Segment_2(h22, h23));
	segments.push_back(Segment_2(h23, h24));
	segments.push_back(Segment_2(h24, h21));

	segments.push_back(Segment_2(h31, h32));
	segments.push_back(Segment_2(h32, h33));
	segments.push_back(Segment_2(h33, h34));
	segments.push_back(Segment_2(h34, h31));

	Arrangement_2 env;
	CGAL::insert_non_intersecting_curves(env, segments.begin(), segments.end());

	// The query points are generated by uniform distribution limited inside the environment outer boundary
	std::vector<Point_2> queries;
	queries.push_back(Point_2(-10.9646822048, -29.6409008578)); // RED
	queries.push_back(Point_2(6.81170570819, -13.2484130172)); // GREEN - Error occurs with this query
	queries.push_back(Point_2(27.2799412588, -5.30534725071)); // BLUE
	queries.push_back(Point_2(-48.8913296027, -35.6313525617)); // YELLOW

	size_t n_queries = queries.size();
	for (size_t i = 0; i < n_queries; i++) {
		try {
			Point_2 query_point = queries[i];
			std::cout << "Query: " << query_point << std::endl;

			Arrangement_2::Face_const_handle * face;
			CGAL::Arr_naive_point_location<Arrangement_2> pl(env);
			CGAL::Arr_point_location_result<Arrangement_2>::Type obj = pl.locate(query_point);
			face = boost::get<Arrangement_2::Face_const_handle> (&obj);

			Polygon_2 vpoly;
			Arrangement_2 output_arr;
			TEV tev(env);

			// Runtime Error is thrown by this line !!
			Face_handle fh = tev.compute_visibility(query_point, *face, output_arr);

			std::cout << "Regularized visibility region of q has " << output_arr.number_of_edges() << " edges." << std::endl;
			std::cout << "Boundary edges of the visibility region:" << std::endl;

			Arrangement_2::Ccb_halfedge_circulator curr = fh->outer_ccb();
			std::cout << "[" << curr->source()->point() << " -> " << curr->target()->point() << "]" << std::endl;
			vpoly.push_back(curr->source()->point());

			while (++curr != fh->outer_ccb()) {
				std::cout << "[" << curr->source()->point() << " -> " << curr->target()->point() << "]"<< std::endl;
				vpoly.push_back(curr->source()->point());
			}

			CGAL::draw(vpoly);
		} catch(std::exception& e) {
			std::cerr << std::string(e.what()) << std::endl;
		}
	}

	return 0;
}
```

At the specified error line, I get a runtime error of ```CGAL::bad_object_cast: failed conversion using CGAL::object_cast``` (for the green one). This occurs quite often with different random queries, but sometimes it may not throw this exception _while the agents are stationary_. If the computation succeeds without errors, it gives good results. I just don't understand why sometimes it fails to compute.

The visual of the environment and the query points:
![Figure_1](https://user-images.githubusercontent.com/44246073/117544041-1efcda80-b028-11eb-986b-876a66fd2395.png)

## Environment

* Operating system: Ubuntu 16.04.6 LTS 64-bit
* Compiler: g++ 5.4.0 (through catkin build ~ cmake)
* Release or debug mode: Release
* Specific flags used: -std=gnu+11 -fext-numeric-literals
* CGAL version: 5.3
* Boost version: 1.66
* Other libraries versions if used (Eigen, TBB, etc.): Eigen-3.3.7

Kind regards,

Burak

**Comment by BurakHocaoglu** [comment]
Thanks for returning, as for the questions:
* Yes I'm using CGAL from it's master branch (I guess I cloned it a couple weeks ago). I, unnecessarily, tried to build in the traditional way (```mkdir build; cmake bla bla; make```), and it generated a file named ```VERSION``` in which ```5.3``` was written.
* Well, when I compiled the examples in CGAL and my own workspace, both used g++ 5.4.0 and I didn't get any errors. In my system, I also have g++-8 installed, but neither compilation processes indicated it's usage.

As for my issue, I noticed the variant type, but I gave queries that are inside the environment so that point location would return a ```Face_handle``` (or so I thought, looking at ```simple_polygon_visibility.cpp``` example). Is there any way to guarantee a type-safe way to generate general visibility polygon from any valid location in the environment? The agents will move and the queries will change. Some of them will result in a ```Face_handle```, some don't.

Thanks

**Comment by lrineau** [comment]
Hi Burak,

So you use CGAL `master` branch, that is about to become CGAL-5.3-beta1. You are lucky that it works with compiler g++ 5.4.0, because we do not test it, and it does not implement fully C++14 that CGAL requires.

As for you real question, about computing visibility, I am not familiar with that package. Maybe @efifogel could help (or @mhsaar he is still reading the mails from Github)... When your starting point lies on the boundary of a face (on an edge, or a vertex), you have to decide in which face of the arrangement you want to compute the visibility. The arrangement data structure gives your an API for walk in the arrangement graph, and in particular you can:
  - for an edge, access the two faces that are incident to the edge,
  - for a vertex, access all the edges or faces around that vertex.

I hope that can help.

**Comment by BurakHocaoglu** [comment]
Hello @lrineau, 

Thanks for the info. I've changed the kernel from inexact to exact, and for now it seems to be working without errors, but only for face handles. At the moment, I'm trusting the fact that the agents will have a non-zero physical radius that will put them away from the outer boundaries of the environment as well as from the holes / obstacles, which I hope will lead the point location function to return a ```Face_const_handle``` variant. If a further error happens, I'll ask @efifogel or @mhsaar .

Thanks for the help...

(Closing the issue for now)
