### ISSUE TITLE
wrong with cgal/Mesh_3/examples/Mesh_3/remesh_polyhedral_surface.cpp

### ISSUE THREAD

**Issue by Frank-Dz** [CGAL/cgal#4412]
## Issue Details

when I ran the dome 'cgal/Mesh_3/examples/Mesh_3/remesh_polyhedral_surface.cpp'
there were something wrong with the code: 

C:\local\CGAL-4.11.3\include\CGAL/internal/boost/array_binary_tree.hpp(54): error C2143: Syntax error: missing ", "(before" < ")
```
\\ ...
struct children_type {
    struct iterator
        : ::boost::iterator<std::forward_iterator_tag,
            //JT: the iterator type is "forward" and not "bidirectional",
            //because it does not implement unary operator--
            ArrayBinaryTreeNode,
            difference_type, array_binary_tree_node*, ArrayBinaryTreeNode&>
    { // replace with iterator_adaptor implementation -JGS
\\...
```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Win 64
* Compiler: VS15
* Release or debug mode: Release
* CGAL version:  4.11.3
* Boost version: 1.69.0

**Comment by afabri** [comment]
Please upgrade from 4.11.3 to a more recent version.

**Comment by Frank-Dz** [comment]
Dear Andreas,


Thanks, I will have a try! Plus, I wonder if CGAL provide a method of sampling on the surface adaptively, just like feature regions on the mesh will generate relatively dense samples.


Best regards,


Zhiyang


On 12/12/2019 22:30，Andreas Fabri<notifications@github.com> wrote：

Please upgrade from 4.11.3 to a more recent version.

**Comment by qiancao** [comment]
Hmmm, just ran into the same issue. So... this is just broken? I need to use an earlier version of CGAL because the library I'm using won't work with CGAL 5.0+. The authors of my code used 4.8.2, so it's a problem with my toolchain? Any ideas?
