### ISSUE TITLE
Error in master about swap

### ISSUE THREAD

**Issue by gdamiand** [CGAL/cgal#4668]
## Issue Details

With CGAL master, I have errors (when compiling some personal code) about CGAL::swap in CGAL/Lazy_exact_nt.h.

My code compile with 5.0 and 5.0.2.

Cf errors here

https://gist.github.com/gdamiand/fcb0519927cdb539dccfd52975c5a129

## Source Code

I don't have a minimal example.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 18.04 64 bits
* Release or debug mode: Both
* CGAL version: master

**Comment by sloriot** [comment]
Do you also have it with CGAL 5.0? What about 4.14.X?

**Comment by gdamiand** [comment]
I found the commit that break my code:
3e4c0d28e5239327357e763249372026f052c134

If I comment the swap method in Lazy_exact_nt my code compile with master.

I don't understand why and how to solve this error.

@mglisse any idea ?

**Comment by mglisse** [comment]
A testcase (doesn't have to be minimal) would be nice, possibly even just preprocessed sources. As a workaround, does it help if you cast to Handle& instead of Base& inside swap (and possibly move the inclusion of Handle.h higher)?

**Comment by gdamiand** [comment]
If I replace the cast Base& by Handle& I have the following error:

/home/gdamiand/sources/cgal/Number_types/include/CGAL/Lazy_exact_nt.h:387:58: error: no matching function for call to ‘swap(CGAL::Handle&, CGAL::Handle&)’
   { swap(static_cast<Handle&>(a), static_cast<Handle&>(b)); }

even moving the inclusion of Handle.h higher...

**Comment by gdamiand** [comment]
Here 

https://gist.github.com/gdamiand/23d88e239fc68036e5e9ab5544c5514f

a standalone cpp file to reproduce this error (result of pre-processing of my program, where I remove a lot of code).

**Comment by mglisse** [comment]
/home/gdamiand/sources/cgal/STL_Extension/include/CGAL/Handle_for.h
/home/gdamiand/sources/rpfc/src/CGAL/Handle.h

You seem to be mixing different CGAL versions, that's not supported.

**Comment by gdamiand** [comment]
Oups, really sorry for the noise. Indeed I forgot this local patch.
Again sorry, and thanks @mglisse for your help.
