### PR TITLE
Aos 2 surface sweep

### PR DESCRIPTION
**Pull request by efifogel**
## Summary of Changes

1. The changes introduced by this branch do not affect the exposed API whatsoever. 
2. I've change the name of the main directory that corresponds to the "2D Intersection of Curves" package from Sweep_line_2 to Surface_sweep_2. It's a better name in general, and it also matches the name of the directory that holds the 2D arrangement code, namely Arrangement_on_surface_2.
3. Sometime ago Andreas and perhaps others moved files from the Aos_2 directory to the Sl_2 (Now Ss_2). The move was done a bit hastily. I've moved one file that was left out, and I moved back some files that shouldn't have been moved in the first place (naturally, updating the included license file.)
4. In the new Ss_2 I've introduced a namespace, namely Surface_sweep_2. However, I'm using it at this point only internally, so the exposed free functions are not affected.
5. The changes where made in order to get rid of the use of 'void *' and castings (both C and C++ styles) which where used to handle inter dependencies. For example, the surface sweep uses types called Event and Subcurve, and each type contains references to object of the other. Now the code has better type checking and I manage to optimize it a bit, so it is more efficient space and time wise.
6. I've also fixed the scheme of instantiation so that the surface-sweep stuff can be exposed (once the appropriate documentation is provided as part of a formal feature submission). For example, the main sweep template is parametrized only by a visitor, and the visitor is parametrized by the traits, the event, the subcurve, and the allocator. (In the past, several types where parametrized by several other and all had defaults, which obviously didn't make sense). In particular, I've fixed the definition of the Allocator so that a user of the sweep can provide her own.
7. I had to use curiously recurring template pattern (CRTP) in several places and they are intermixed. Unfortunately, I cannot use C++11 features, but I managed. Everything compiles on G++ 4.8.4 and VC 14. I have a feeling that I'll have to work on it to get older VC versions to work, we'll see.

## Release Management

* Affected package(s): "2D Intersection of Curves" and "2D Arrangements"
* Issue(s) solved (if any): see above
* Feature/Small Feature (if any): no

### CODE REVIEW

**Comment by sloriot** [comment]
@efifogel Travis failed with several errors:
- _The following files are referenced in the documentation but do not exist:_ `Surface_sweep_2/doc/Surface_sweep_2/CGAL/Sweep_line_2_algorithms.h`
- Compilation errors in [BSO_2](https://travis-ci.org/CGAL/cgal/jobs/250354791)
There are others packages with compilation errors but I guess they are all related to the latter.

File: Arrangement_on_surface_2/include/CGAL/Arr_batched_point_location.h [hunk 1]
```diff
@@ -24,61 +21,75 @@
...
 
   // Go over all arrangement edges and collect their associated x-monotone
   // curves. To each curve we attach a halfedge handle going from right to
   // left.
-  std::vector<Bpl_x_monotone_curve_2>  xcurves_vec(arr.number_of_edges());
-  Edge_const_iterator                  eit;
-  unsigned int                         i = 0;
+  std::vector<Bpl_x_monotone_curve_2> xcurves_vec(arr.number_of_edges());
+  Edge_const_iterator eit;
+  size_t i(0);
```
Comment (sloriot) [inline Arrangement_on_surface_2/include/CGAL/Arr_batched_point_location.h]: std::size_t

File: Arrangement_on_surface_2/include/CGAL/Arr_bounded_planar_topology_traits_2.h [hunk 2]
```diff
@@ -190,189 +191,162 @@ class Arr_bounded_planar_topology_traits_2 :
...
+  typedef Arrangement_on_surface_2<Gt2, Self>                   Arr;
+
+public:
+  // The following definitions of helper functions use a C++11 features called
+  // alias template. This feature can be mimiked by non C++11 support simply by
+  // defining a type that inherits from the template we need to alias.  However,
+  // the non-C++11 code requires the (re)definition of all constructors of the
+  // derived class. The non-C++11 code follows the commented out C++11 code.
+  // When we move to C++11 we can use the more elgant code.
+#if 0
```
Comment (sloriot) [inline Arrangement_on_surface_2/include/CGAL/Arr_bounded_planar_topology_traits_2.h]: There are some macros in CGAL to enable the code on platforms that support template aliases.

File: Arrangement_on_surface_2/include/CGAL/Arr_spherical_topology_traits_2.h [hunk 3]
```diff
@@ -314,157 +306,139 @@ class Arr_spherical_topology_traits_2 {
...
-  template <typename OutputIterator_>
-  struct Sweep_line_batched_point_location_visitor :
-    public Arr_batched_pl_sl_visitor<BplHelper, OutputIterator_>
+  // The following definitions of helper functions use a C++11 features called
+  // alias template. This feature can be mimiked by non C++11 support simply by
+  // defining a type that inherits from the template we need to alias.  However,
+  // the non-C++11 code requires the (re)definition of all constructors of the
+  // derived class. The non-C++11 code follows the commented out C++11 code.
+  // When we move to C++11 we can use the more elgant code.
+#if 0
```
Comment (sloriot) [inline Arrangement_on_surface_2/include/CGAL/Arr_spherical_topology_traits_2.h]: Same here

File: Arrangement_on_surface_2/include/CGAL/Arr_unb_planar_topology_traits_2.h [hunk 4]
```diff
@@ -165,241 +164,206 @@ class Arr_unb_planar_topology_traits_2 :
...
-  template <class OutputIterator_>
-  struct Sweep_line_batched_point_location_visitor :
-    public Arr_batched_pl_sl_visitor<BplHelper, OutputIterator_>
+  // The following definitions of helper functions use a C++11 features called
+  // alias template. This feature can be mimiked by non C++11 support simply by
+  // defining a type that inherits from the template we need to alias.  However,
+  // the non-C++11 code requires the (re)definition of all constructors of the
+  // derived class. The non-C++11 code follows the commented out C++11 code.
+  // When we move to C++11 we can use the more elgant code.
+#if 0
```
Comment (sloriot) [inline Arrangement_on_surface_2/include/CGAL/Arr_unb_planar_topology_traits_2.h]: same here

File: Arrangement_on_surface_2/include/CGAL/Arrangement_2/Arrangement_on_surface_2_global.h [hunk 5]
```diff
@@ -12,48 +12,51 @@
...
 /*! \file
  * Global insertion functions for the Arrangement_2 class.
  */
 
 #include <boost/type_traits.hpp>
 #include <boost/mpl/if.hpp>
+#include <boost/type_traits.hpp>
+#include <list>
 
+#include <CGAL/license/Arrangement_on_surface_2.h>
```
Comment (sloriot) [inline Arrangement_on_surface_2/include/CGAL/Arrangement_2/Arrangement_on_surface_2_global.h]: The license include directive should be right after the include guards

File: Arrangement_on_surface_2/include/CGAL/Arrangement_2/Arrangement_on_surface_2_global.h [hunk 6]
```diff
@@ -182,7 +187,7 @@ void insert(Arrangement_on_surface_2<GeomTraits, TopTraits>& arr,
     std::cout << "xxxxxxxxxxxx" << std::endl;
   }
 */
-  arr_zone.init (c, pl);
+  arr_zone.init(c, pl);
```
Comment (sloriot) [inline Arrangement_on_surface_2/include/CGAL/Arrangement_2/Arrangement_on_surface_2_global.h]: Since you are cleaning the files, any reason to keep the part with the _Needs to be deleted!!!_ flag?

File: Arrangement_on_surface_2/include/CGAL/Surface_sweep_2/Arr_construction_subcurve.h [hunk 7]
```diff
@@ -0,0 +1,220 @@
...
+  typedef Geometry_traits_2                             Gt2;
+  typedef SurfaceSweepBaseCurve<Gt2, Event, Allocator, Subcurve>
+                                                        Base;
+
+public:
+  typedef typename Gt2::X_monotone_curve_2              X_monotone_curve_2;
+  typedef Event*                                        Event_ptr;
+  typedef std::list<unsigned int>                       Halfedge_indices_list;
+
+  /*! Construct deafult. */
```
Comment (sloriot) [inline Arrangement_on_surface_2/include/CGAL/Surface_sweep_2/Arr_construction_subcurve.h]: typo

File: Arrangement_on_surface_2/include/CGAL/Surface_sweep_2/Arr_insertion_sl_visitor.h [hunk 8]
```diff
@@ -0,0 +1,170 @@
...
+   * \param The split point.
+   * \return A handle to the split edge.
+   */
+  virtual Halfedge_handle split_edge(Halfedge_handle he, Subcurve* sc,
+                                     const Point_2& pt);
+  //@}
+};
+
+//-----------------------------------------------------------------------------
+// Memeber-function definitions:
```
Comment (sloriot) [inline Arrangement_on_surface_2/include/CGAL/Surface_sweep_2/Arr_insertion_sl_visitor.h]: typo

File: Arrangement_on_surface_2/include/CGAL/Surface_sweep_2/Arr_no_intersection_insertion_sl_visitor.h [hunk 9]
```diff
@@ -12,66 +12,81 @@
...
+/*! \class Arr_no_intersection_insertion_sl_visitor
+ *
  * A sweep-line visitor for inserting new curves into an existing arrangement
  * embedded on a surface, where these curves are interior-disjoint from all
  * existing arrangement edges and vertices (so no intersections occur).
  */
-template <typename Helper_> 
-class Arr_basic_insertion_sl_visitor : public Helper_::Parent_visitor {
+template <typename Helper_, typename Visitor_ = Default>
+class Arr_no_intersection_insertion_sl_visitor :
```
Comment (sloriot) [inline Arrangement_on_surface_2/include/CGAL/Surface_sweep_2/Arr_no_intersection_insertion_sl_visitor.h]: General remark: you might want to replace `_sl_` by `_ss_` everywhere.

File: Documentation/doc/Documentation/dependencies [hunk 10]
```diff
@@ -57,7 +57,7 @@ Principal_component_analysis
 STL_Extension
 Skin_surface_3
 Snap_rounding_2
-Sweep_line_2
+Surface_sweep_2
```
Comment (sloriot) [inline Documentation/doc/Documentation/dependencies]: This change will require a redirect in the apache file of the doc so that latest will be correctly redirected.

File: Surface_sweep_2/examples/Surface_sweep_2/plane_sweep.cpp [hunk 11]
```diff
@@ -1,18 +1,16 @@
...
 #include <list>
 
-typedef CGAL::Quotient<CGAL::MP_Float>                  NT;
-typedef CGAL::Cartesian<NT>                             Kernel;
-typedef Kernel::Point_2                                 Point_2;
-typedef CGAL::Arr_segment_traits_2<Kernel>              Traits_2;
-typedef Traits_2::Curve_2                               Segment_2;
+#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
+#include <CGAL/Arr_segment_traits_2.h>
+#include <CGAL/Surface_sweep_2_algorithms.h>
```
Comment (sloriot) [inline Surface_sweep_2/examples/Surface_sweep_2/plane_sweep.cpp]: The header renaming is a breaking change that must be announced in Installation.html + the former header should still be kept with a redirect to the new header. You can use macros for this purpose such as in `AABB_tree/include/CGAL/AABB_polyhedron_triangle_primitive.h` for example.

File: Surface_sweep_2/include/CGAL/Surface_sweep_2/Curve_pair.h [hunk 12]
```diff
@@ -12,103 +12,84 @@
...
+  Curve_pair (Subcurve* sc1, Subcurve* sc2)
   {
-    // The smallest pointer will be the first. 
-    if(sc1 < sc2)
-      m_pair = std::make_pair (sc1,sc2);
-    else
-      m_pair = std::make_pair (sc2,sc1);
+    // The smallest pointer will be the first.
+    if (sc1 < sc2) m_pair = std::make_pair (sc1,sc2);
+    else m_pair = std::make_pair (sc2,sc1);
```
Comment (sloriot) [inline Surface_sweep_2/include/CGAL/Surface_sweep_2/Curve_pair.h]: there is a function `CGAL::make_sorted_pair()` in `CGAL/utility.h`

**Comment by efifogel** [comment]
Thanks for the detailed review!
I've fixed all the above except for 2 items:
1. I did not enable the code that uses template aliases, and
2. I did not do anything regarding the need to redirect in the Apache file
of the doc so that latest will be correctly redirected.

In particular, I've introduced

Surface_sweep_2/include/CGAL/Sweep_line_2_algorithms.h

in order to maintain backward compatibility.

Regarding the 2 items I did not do.
1. I couldn't find a macro that conditionally enables template aliases.
I'll be happy to use if exists (or even introduce if not).
2. I'm not familiar with the Apache settings. Is there anything that needs
to be done in the code base?
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
For 1 you can use `#if !defined(BOOST_NO_CXX11_TEMPLATE_ALIASES) && !defined(BOOST_NO_TEMPLATE_ALIASES)` to handle both older and newer versions of boost. Note that you can also introduce `CGAL_CFG_NO_CPP0X_TEMPLATE_ALIASES` in `Installation/include/CGAL/config.h` if you want.

For 2, this is something @lrineau will do when integrating the branch. I've added a special label to the PR so that we don't forget.

**Comment by efifogel** [comment]
Thanks.
I've introduced CGAL_CFG_NO_CPP0X_TEMPLATE_ALIASES in
Installation/include/CGAL/config.h

The branch is ready for integration.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
I have killed the Travis job, because this PR:
  - is not for CGAL-4.11,
  - and will probably be modified multiple times before it is integration into CGAL.

**Comment by efifogel** [comment]
I don't see a reason not to introduce it to 4.11.
It is ready and I'm not aware of any more changes needed.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
I see several reasons:
1. the code freeze for CGAL-4.11 was two weeks ago, even before you created this PR,
2. 252 files are changed, and it cannot be considered as a small low-risk change,
3. the PR has never been tested so far, and until today it was failing in Travis, and I plan to finish CGAL-4.11-beta1 tomorrow.

Do you have a good reason to force it into CGAL-4.11?

**Comment by lrineau** [comment]
115 files are actually modified, if we skip renamings without change of the file. That is still a lot.

**Comment by efifogel** [comment]
This is the reason I want to get it out.
Then, other changes and fixes are done on top of it.
Anyhow, as I've said the PR is ready as far as I can tell. If you have
other pressing PRs I understand.



   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
That is not the others PR that are pressing but the schedule. Such big a change should be done early in the release cycle, and certainly not after the code freeze. For CGAL-4.12, the timing is perfect.

**Comment by efifogel** [comment]
ok, no problem.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
@efifogel There are some new warnings. See [test results](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-4.shtml). I  haven't checked for new errors.

**Comment by efifogel** [comment]
Thanks for pointing it out.
All relevant warnings have been handled.
The errors are unrelated.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
@efifogel  You still have warnings in Kernel_23, Boolean_operations_2, Minkowski_sum_2, and Polygon_Demo.
See [test results](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-6.shtml).

**Comment by efifogel** [comment]
Thanks for watching my back.
All fixed now.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
One warning remains: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-9/Surface_sweep_2/TestReport_lrineau_CentOS7-ICC-Release.gz
It is a strange one. Maybe an issue with the testsuite script?

**Comment by efifogel** [comment]
I don't even know how to produce it...

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
The warning seems to be reported by ICC [see](http://www.itkeyword.com/doc/4956007848491213829/problems-setting-environment-variables-for-intel-c-composer-gcc-not-found)/ I don't know why only `Surface_sweep_2, `Snap_rounding_2`, and `Arrangement_on_surface_2` have the warning. But it is probably not a coincidence that theses test directories have custom `cgal_test_base` scripts. @lrineau @maxGimeno Any idea?

**Comment by lrineau** [comment]
You are right: that is because the `cgal_test` scripts in those directories calls a sub-level bash, and that platform has `BASH_ENV=/etc/profile.d/intel.sh` in its environment. Our file `/etc/profile.d/intel.sh` should have a sort of guard variable, to prevent its reloading when it has already been evaluated once.

**Comment by lrineau** [comment]
This PR has been left untouched for a month. Is that on purpose?

**Comment by efifogel** [comment]
It's my fault.
I'll get to it in a couple of days.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
Thanks Efi. That's fine. I just wanted to avoid that it was untouched/stalled because of me.

**Comment by lrineau** [comment]
Issues with the new SPDX identifiers (cc @sloriot):
- https://travis-ci.org/CGAL/cgal/jobs/303048767#L2493

**Comment by sloriot** [comment]
Should be fixed

**Comment by lrineau** [comment]
https://travis-ci.org/CGAL/cgal/jobs/305259095#L2497
```
The following files do not have a SPDX license identifier:
Surface_sweep_2/include/CGAL/Surface_sweep_2/Subcurves_visitor.h
```

**Comment by lrineau** [comment]
This still fails in Travis: https://travis-ci.org/CGAL/cgal/jobs/305772090#L6819

**Comment by efifogel** [comment]
ok, I've renamed some left overs sweep_line with surface_sweep.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

File: .travis.yml [hunk 13]
```diff
@@ -1,59 +1,59 @@
-language: cpp
```
Comment (MaelRL) [inline .travis.yml]: This file (`.travis.yml`) and `.travis/package.txt` are generated with scripts. If the trailing whitespace is removed, the script should be updated. Otherwise, if you rerun the script, the trailing whitespace is back and you get the inverse diff.

**Comment by sloriot** [comment]
Tested in [CGAL-4.12-Ic-124](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-124)

@lrineau  For the next release, we need to add a redirect in the apache file of the doc so that latest will be correctly redirected from `Sweep_line_2` to `Surface_sweep_2`. I open issue #2699
