### ISSUE TITLE
GCC build error on Win64 (only) when using PMP::triangulate_faces w/ Gmp (regression in 5.3+)

### ISSUE THREAD

**Issue by ochafik** [CGAL/cgal#6308]
## Issue Details

Compilation of a simple `triangulate_faces(Surface_mesh<Epeck>)` snippet (see full repro code below) fails to compile on Win64 w/ GCC since 5.3.1 (5.4 included; I couldn't test 5.3.0), but worked fine up to 5.2.4 / still works on Win32.

Using the mingw toolchain, same result either compiling in Windows itself w/ msys2 or cross-compiling from Linux w/ the mxe environment.

(Context: OpenSCAD is [adopting PMP corefinement and Suface_mesh](https://github.com/openscad/openscad/pull/4087)!)

Here's the error message:

```
In file included from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Number_types/internal/Exact_type_selector.h:25,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Exact_kernel_selector.h:26,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Filtered_kernel.h:22,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Exact_predicates_exact_constructions_kernel.h:21,
                 from bug.cc:2:
/mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Lazy_exact_nt.h: In instantiation of 'void CGAL::Lazy_exact_Cst<ET, X>::update_exact() const [with ET = __gmp_expr<__mpq_struct [1], __mpq_struct [1]>; X = long long unsigned int]':
/mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Lazy_exact_nt.h:152:8:   required from here
/mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Lazy_exact_nt.h:153:17: error: call of overloaded '__gmp_expr(const long long unsigned int&)' is ambiguous
  153 |     auto* pet = new typename Lazy_exact_nt_rep<ET>::Indirect(cste);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/is_convertible.h:23,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Rational_traits.h:23,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/number_type_basic.h:40,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/basic.h:28,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Cartesian/Cartesian_base.h:20,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Simple_cartesian.h:20,
                 from /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Exact_predicates_exact_constructions_kernel.h:20,
                 from bug.cc:2:
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(double)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(float)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(long unsigned int)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(long int)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(short unsigned int)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(short int)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(unsigned int)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(int)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(unsigned char)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1661:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(signed char)'
 1661 |   __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1648:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(__gmp_expr<__mpq_struct [1], __mpq_struct [1]>&&)'
 1648 |   __gmp_expr(__gmp_expr &&q)
      |   ^~~~~~~~~~
/mxe/usr/x86_64-w64-mingw32.static.posix/include/gmpxx.h:1642:3: note: candidate: '__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(const __gmp_expr<__mpq_struct [1], __mpq_struct [1]>&)'
 1642 |   __gmp_expr(const __gmp_expr &q)
      |   ^~~~~~~~~~
```

## Source Code

Here's how to reproduce the issue locally easily:

```bash
docker run --entrypoint=/bin/bash -it openscad/mxe-x86_64-openscad:cgal-5.4
```

```bash
export MXEDIR=/mxe
. scripts/setenv-mingw-xbuild.sh -64

echo '
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Polygon_mesh_processing/triangulate_faces.h>
#include <CGAL/Surface_mesh.h>

int main() {
	CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epeck>> mesh;
	CGAL::Polygon_mesh_processing::triangulate_faces(mesh);
}
'> bug.cc

/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.static.posix-g++ -std=c++14 \
	-I/mxe/usr/x86_64-w64-mingw32.static.posix/include \
	-DCGAL_USE_GMPXX=1 \
	-o bug.cc.obj -c bug.cc 
```

## Environment

* Operating system: Windows 64 bits (or Linux 64 bits w/ minwg cross-compiling env for Windows 64 bits)
* Compiler: x86_64-w64-mingw32.static.posix-g++ (GCC) 11.2.0
* Release or debug mode: unsure (both?)
* Specific flags used (if any): -DCGAL_USE_GMPXX=1
* CGAL version: 5.3.x, 5.4 (was working fine prior to that, e.g. 5.2.4)
* Boost version: 1_78
* Other libraries versions if used (Eigen, TBB, etc.): __GNU_MP__ 6.1.2

**Comment by mglisse** [comment]
Looks like something in CGAL converts a size_t to FT, whereas we don't guarantee that possibility for our number types. Too bad gcc doesn't show what requires this instantiation.

**Comment by mglisse** [comment]
https://github.com/CGAL/cgal/blob/38c4ebd4440b94ec999c8f89457569a994e20bca/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h#L1365-L1367

`Simple_cartesian<mpq_class>` points at the location much more clearly than Epeck.

**Comment by sloriot** [comment]
Should be fixed by #6309

**Comment by t-paul** [comment]
Unfortunately that does not seem to fix the issue. Compilation still fails after applying the change inside the test container.

**Comment by t-paul** [comment]
Here's another one with `Epeck`:

https://github.com/CGAL/cgal/blob/e5dfd6c8ebf79b91e73728aeba44f3378f3e8dda/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h#L1247

https://github.com/CGAL/cgal/blob/e5dfd6c8ebf79b91e73728aeba44f3378f3e8dda/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h#L1289

The 2 changes together seem to fix the `bug.cc` compilation. I have to run another full build to verify the application build, but that takes a while.

**Comment by t-paul** [comment]
Successfully tested with full application build. That's still with my change using `int` for that `n` variable, but I don't expect that to be different with the official patch regarding the compilation issue.

Rebuild with the diff from #6309 is running now.
