### ISSUE TITLE
Missing boost header in number_utils.h causes compilation error on CGAL-5.6.2

### ISSUE THREAD

**Issue by cagseylan** [CGAL/cgal#8897]
## Issue Details

While working with CGAL 5.6.2, I attempted to compile the `Triangulation_2` example to verify my setup. During compilation, I encountered the following error in `number_utils.h`:

```
~/Desktop/cgal-install/include/CGAL/number_utils.h:197:22: error: no type named 'if_c' in namespace 'boost::mpl'
  197 | typename boost::mpl::if_c<
      | ~~~~~~~~~~~~~~~~~~~~~^~~~
~/Desktop/cgal-install/include/CGAL/number_utils.h:197:26: error: expected unqualified-id
  197 | typename boost::mpl::if_c<
      |
```

This error is caused by a missing include directive for `#include <boost/mpl/if.hpp>`.

After manually adding this include to `number_utils.h`, the example compiled and ran successfully.

I checked CGAL v6.0.1, and noticed this header is properly included there, so the issue no longer exists in the latest version.

I'm not opening a fix PR since this appears to have already been resolved in 6.x. However, I wanted to document this in case other users working with 5.6.2 encounter the same issue or for reference by the CGAL team. 

## Source Code

The error occurs when compiling the official CGAL example for `Triangulation_2`.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): MacOS Sequoia 15.4.1 
* Compiler: Apple clang version 17.0.0
* Release or debug mode: Release
* Specific flags used (if any): - 
* CGAL version: 5.6.2
* Boost version: 1.88
* Other libraries versions if used (Eigen, TBB, etc.): -

**Comment by sloriot** [comment]
Note that it has already been added in the 5.6.x-branch so it will be present in 5.6.3
