### ISSUE TITLE
SFINAE issue in BGL for Surface_mesh

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1061]
@maxGimeno @afabri I have managed to reduce the compilation error to the following code:
```C++
#define BUG 1

#if BUG
#  include <CGAL/boost/graph/properties_Surface_mesh.h>
#endif

#include <boost/variant.hpp>

namespace CGAL {
  struct A {};
  struct B {};
}

namespace boost {

  void func() {
    const boost::variant<CGAL::A, CGAL::B> v;
    get<const CGAL::A>(&v);
  }
}

int main()
{
  boost::func();
}
```
(See https://gist.github.com/lrineau/4e723302e081842c20e1ed02a1c59b4c)

That code does not compile with CGAL-4.7, CGAL-4.8, or `master`. If the macro `BUG` is defined to 0, then the header `<CGAL/boost/graph/properties_Surface_mesh.h>` is not included, and the code compiles.

The compilation error:
```
In file included from /usr/include/c++/5.3.1/x86_64-redhat-linux/bits/c++allocator.h:33:0,
                 from /usr/include/c++/5.3.1/bits/allocator.h:46,
                 from /usr/include/c++/5.3.1/ext/alloc_traits.h:38,
                 from /usr/include/c++/5.3.1/bits/stl_construct.h:61,
                 from /usr/include/c++/5.3.1/bits/stl_tempbuf.h:60,
                 from /usr/include/c++/5.3.1/bits/stl_algo.h:62,
                 from /usr/include/c++/5.3.1/algorithm:62,
                 from /home/lrineau/Git/cgal/Installation/include/CGAL/config.h:331,
                 from /home/lrineau/Git/cgal/STL_Extension/include/CGAL/assertions.h:25,
                 from /home/lrineau/Git/cgal/BGL/include/CGAL/boost/graph/properties_Surface_mesh.h:24,
                 from /home/lrineau/tmp/test/essai.cpp:4:
/usr/include/c++/5.3.1/ext/new_allocator.h: In instantiation of ‘class __gnu_cxx::new_allocator<const CGAL::A>’:
/usr/include/c++/5.3.1/bits/allocator.h:92:11:   required from ‘class std::allocator<const CGAL::A>’
/usr/include/c++/5.3.1/ext/alloc_traits.h:172:38:   required from ‘struct __gnu_cxx::__alloc_traits<std::allocator<const CGAL::A> >’
/usr/include/c++/5.3.1/bits/stl_vector.h:75:28:   required from ‘struct std::_Vector_base<const CGAL::A, std::allocator<const CGAL::A> >’
/usr/include/c++/5.3.1/bits/stl_vector.h:214:11:   required from ‘class std::vector<const CGAL::A, std::allocator<const CGAL::A> >’
/home/lrineau/Git/cgal/Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h:337:45:   required from ‘class CGAL::Surface_mesh<const CGAL::A>::Property_array<const CGAL::A>’
/home/lrineau/Git/cgal/Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h:649:7:   required from ‘class CGAL::Surface_mesh<const CGAL::A>::Property_map<CGAL::SM_Vertex_index, const CGAL::A>’
/home/lrineau/Git/cgal/Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h:2429:39:   required from ‘class CGAL::Surface_mesh<const CGAL::A>’
/home/lrineau/Git/cgal/BGL/include/CGAL/boost/graph/graph_traits_Surface_mesh.h:50:37:   required from ‘struct boost::graph_traits<CGAL::Surface_mesh<const CGAL::A> >’
/home/lrineau/Git/cgal/BGL/include/CGAL/boost/graph/properties_Surface_mesh.h:233:33:   required by substitution of ‘template<class Point> Point& boost::get(boost::vertex_point_t, const CGAL::Surface_mesh<Point_3>&, typename boost::graph_traits<CGAL::Surface_mesh<Point_3> >::vertex_descriptor) [with Point = const CGAL::A]’
/home/lrineau/tmp/test/essai.cpp:18:26:   required from here
/usr/include/c++/5.3.1/ext/new_allocator.h:93:7: error: ‘const _Tp* __gnu_cxx::new_allocator<_Tp>::address(__gnu_cxx::new_allocator<_Tp>::const_reference) const [with _Tp = const CGAL::A; __gnu_cxx::new_allocator<_Tp>::const_pointer = const CGAL::A*; __gnu_cxx::new_allocator<_Tp>::const_reference = const CGAL::A&]’ cannot be overloaded
       address(const_reference __x) const _GLIBCXX_NOEXCEPT
       ^
/usr/include/c++/5.3.1/ext/new_allocator.h:89:7: error: with ‘_Tp* __gnu_cxx::new_allocator<_Tp>::address(__gnu_cxx::new_allocator<_Tp>::reference) const [with _Tp = const CGAL::A; __gnu_cxx::new_allocator<_Tp>::pointer = const CGAL::A*; __gnu_cxx::new_allocator<_Tp>::reference = const CGAL::A&]’
       address(reference __x) const _GLIBCXX_NOEXCEPT
       ^
```

There is a hard error in a substitution of parameters for a `get` function in  `<CGAL/boost/graph/properties_Surface_mesh.h>`.

**Comment by lrineau** [comment]
@mglisse What is the best solution? I can `boost::lazy_disable_if`, to disable the `get` functions from CGAL BGL, if the parameter `Point` is `const`. Is there something better?

**Comment by mglisse** [comment]
Hmm, inconvenient.
The main bug in my opinion is that everyone (variant, graph, etc) absolutely wants to use the same function name `get`. As an optimization, gcc should also check the number of arguments before doing any instantiation (clang accepts the code, most likely for that reason).
If we were doing C++11, a hack would be `template<class=void, class Point>`, this way `get<Broken>` would not try to substitute anything into Surface_mesh. A corresponding ugly C++03 hack would be `template<class Tag,class Point>typename enable_if<boost::is_same<Tag,PROP>::value,RET>::type get(Tag p,...)`.
With `disable_if` used à la C++03, I am not sure how much guarantee you have that the same error will not occur.
It would make sense to qualify `boost::get` when you know you want the one for `boost::variant`. Not that it would help here since the bad overload is also in namespace boost (I thought this was only necessary with some old compilers and we could put get/put in namespace CGAL now?).

**Comment by lrineau** [comment]
The unqualified call to `get<const Point>` is actually in Boost-1.57.0, in `<boost/variant/get.hpp>`:
```C++
template <typename U, BOOST_VARIANT_ENUM_PARAMS(typename T) >
inline
    typename add_reference<const U>::type
get(
      const boost::variant< BOOST_VARIANT_ENUM_PARAMS(T) >& operand
      BOOST_VARIANT_AUX_GET_EXPLICIT_TEMPLATE_TYPE(U)
    )
{
  // [ skip a static assert ]

    typedef typename add_pointer<const U>::type U_ptr;
    U_ptr result = get<const U>(&operand);

    if (!result)
        boost::throw_exception(bad_get());
    return *result;
}
```

It was "fixed", in the following version, when they introduced `relaxed_get` and `strict_get`.

But anyway, that is a bug that the `get` function template from CGAL, intended to be called by ADL, with such a short and common name, is not SFINAE-friendly.

I have a hack using `lazy_enable_if`. The fix will be in a PR from Maxime later today.

I need to use `lazy_enable_if`, because the return type that you called `RET` in your proposal needs the instantiation of `Surface_mesh<const Point>`, and that leads to a hard error.

**Comment by mglisse** [comment]
Well I was talking about `CGAL_SM_INTRINSIC_PROPERTY(Point&, CGAL::vertex_point_t, vertex_descriptor)` (the one in the error message). But I don't see how what I proposed could result in `Surface_mesh<const Point>`. The whole point is that I make Point the second template parameter, so `get<const Smurf>` does not force anything on Point (`get<Whatever, const Smurf>` would, but it seems less common).
Are const types the only ones that would cause an error? What about `void`, or maybe a reference?

**Comment by lrineau** [comment]
@mglisse The C++11 [`std::is_copy_assignable`][s] or [`boost::is_copy_assignable`][b] would be the right type traits to check, instead of 

[s]: http://en.cppreference.com/w/cpp/types/is_copy_assignable
[b]: http://www.boost.org/doc/libs/1_60_0/libs/type_traits/doc/html/boost_typetraits/reference/is_copy_assignable.html

The Boost version, especially in C++03, is not perfect, but its code has a comment that says:
> For compilers without `decltype`, at least return false on `const` types


@maxGimeno Please modify `boost::is_const` to `boost::is_copy_assignable` in the PR #1063, but, as the logic has to be reversed, transform also the uses of `lazy_disable_if` to `lazy_enable_if`.

**Comment by sloriot** [comment]
Fixed in  #1063
