### PR TITLE
Kernel_23: Add the function  FT  l_infinity_distance() for 2D and 3D points

### PR DESCRIPTION
**Pull request by afabri**
Add the function  `FT  l_infinity_distance(Point_2, Point_2)` as well as the corresponding functor

This is a function where the implementation is in the file
`Kernel_23/include/CGAL/Kernel/function_objects.h`

When the implementation is different for Cartesian and Homogeneous coordinates
the code should go into the `function_objects.h` files
in the packages Cartesian_kernel and Homogeneous_kernel

This fixes the 2D version of the Issue #1624 

Small feature: https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Add_L_Infinity_Distance()

Pre-approved: 18 November 2016

### CODE REVIEW

**Comment by sloriot** [comment]
@maxGimeno This require a small feature. Could you write the page? For the documentation, simply put on the wiki page the change in  `Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h` saying that the functors have been added and the Kernel concept has been updated.
`changes.html` must be also updated.

**Comment by maxGimeno** [comment]
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Add_L_Infinity_Distance()#changes.html

File: Installation/changes.html [hunk 1]
```diff
@@ -169,6 +169,13 @@ <h2 id="release4.10">Release 4.10 </h2>
 <!-- Surface Reconstruction -->
 <!-- Geometry Processing -->
 <!-- Spatial Searching and Sorting -->
+<h3> Kernel_23 </h3>
```
Comment (sloriot) [inline Installation/changes.html]: Wrong category and wrong title. The name should be the package name and the category should be as in the [package description](http://doc.cgal.org/latest/Manual/packages.html)

**Comment by afabri** [comment]
@lrineau  As it is _pre-approved_ it is no longer _not yet approved_, and it was _pre-approved_  and tested, so it might be merged.

**Comment by lrineau** [comment]
It was pre-approved exactly two weeks ago, so it has only been approved today. It will be tested tonight.

**Comment by lrineau** [comment]
Actually, it will not be tested tonight, because it conflicts with #585 that has already been merged in `integration`.

**Comment by lrineau** [comment]
Now that #585 is merged, there are conflicts... You should rebase the branch onto `master`.

**Comment by lrineau** [comment]
There is a compilation error when the exact number type if not Gmpq:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-81/Segment_Delaunay_graph_Linf_2/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.1_Release-LEDA-without-GMP.gz

**Comment by lrineau** [comment]
... Actually that compilation error is not related. See issue #1780 that shows the compilation error in CGAL-4.9.1-I.

**Comment by afabri** [comment]
As it is not related, you maybe can remove Tests failing?

**Comment by lrineau** [comment]
I did remove that label yesterday. Did not I?

**Comment by afabri** [comment]
you did. Sorry, I only saw the red box (that's what red is for) but missed the _and removed_
